//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://www.unicode.org/Public/UCD/latest/ucd/extracted/DerivedCombiningClass.txt
// Last-Modified: 2019-11-13T23:04:40Z
// ETag: "9f802c-28e8b-5974263b51200"

/*
  UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE
  
  See <a href="https://www.unicode.org/copyright.html">Terms of Use</a> for definitions of Unicode Inc.'s
  Data Files and Software.
  NOTICE TO USER: Carefully read the following legal agreement.
  BY DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S
  DATA FILES ("DATA FILES"), AND/OR SOFTWARE ("SOFTWARE"),
  YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
  TERMS AND CONDITIONS OF THIS AGREEMENT.
  IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE
  THE DATA FILES OR SOFTWARE.
  COPYRIGHT AND PERMISSION NOTICE
  Copyright © 1991-2020 Unicode, Inc. All rights reserved.
  Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
  Permission is hereby granted, free of charge, to any person obtaining
  a copy of the Unicode data files and any associated documentation
  (the "Data Files") or Unicode software and any associated documentation
  (the "Software") to deal in the Data Files or Software
  without restriction, including without limitation the rights to use,
  copy, modify, merge, publish, distribute, and/or sell copies of
  the Data Files or Software, and to permit persons to whom the Data Files
  or Software are furnished to do so, provided that either
  (a) this copyright and permission notice appear with all copies
  of the Data Files or Software, or
  (b) this copyright and permission notice appear in associated
  Documentation.
  THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
  ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT OF THIRD PARTY RIGHTS.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
  NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
  DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
  DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
  TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
  PERFORMANCE OF THE DATA FILES OR SOFTWARE.
  Except as contained in this notice, the name of a copyright holder
  shall not be used in advertising or otherwise to promote the sale,
  use or other dealings in these Data Files or Software without prior
  written authorization of the copyright holder.
*/

// Required Modules
import Ranges

// Type Aliases
private typealias _T0 = Unicode.CanonicalCombiningClass
private typealias _T1 = (Unicode.Scalar.Value, _T0)
private typealias _T2 = (AnyRange<UInt32>, _T0)
private typealias _T3 = Array<_T2>

private let __ccc_pair_0: _T1 = (0x315, .init(rawValue: 232))
private let __ccc_pair_1: _T1 = (0x316, .init(rawValue: 220))
private let __ccc_pair_2: _T1 = (0x317, .init(rawValue: 220))
private let __ccc_pair_3: _T1 = (0x318, .init(rawValue: 220))
private let __ccc_pair_4: _T1 = (0x319, .init(rawValue: 220))
private let __ccc_pair_5: _T1 = (0x31a, .init(rawValue: 232))
private let __ccc_pair_6: _T1 = (0x31b, .init(rawValue: 216))
private let __ccc_pair_7: _T1 = (0x321, .init(rawValue: 202))
private let __ccc_pair_8: _T1 = (0x322, .init(rawValue: 202))
private let __ccc_pair_9: _T1 = (0x323, .init(rawValue: 220))
private let __ccc_pair_a: _T1 = (0x324, .init(rawValue: 220))
private let __ccc_pair_b: _T1 = (0x325, .init(rawValue: 220))
private let __ccc_pair_c: _T1 = (0x326, .init(rawValue: 220))
private let __ccc_pair_d: _T1 = (0x327, .init(rawValue: 202))
private let __ccc_pair_e: _T1 = (0x328, .init(rawValue: 202))
private let __ccc_pair_f: _T1 = (0x339, .init(rawValue: 220))
private let __ccc_pair_g: _T1 = (0x33a, .init(rawValue: 220))
private let __ccc_pair_h: _T1 = (0x33b, .init(rawValue: 220))
private let __ccc_pair_i: _T1 = (0x33c, .init(rawValue: 220))
private let __ccc_pair_j: _T1 = (0x345, .init(rawValue: 240))
private let __ccc_pair_k: _T1 = (0x346, .init(rawValue: 230))
private let __ccc_pair_l: _T1 = (0x347, .init(rawValue: 220))
private let __ccc_pair_m: _T1 = (0x348, .init(rawValue: 220))
private let __ccc_pair_n: _T1 = (0x349, .init(rawValue: 220))
private let __ccc_pair_o: _T1 = (0x34a, .init(rawValue: 230))
private let __ccc_pair_p: _T1 = (0x34b, .init(rawValue: 230))
private let __ccc_pair_q: _T1 = (0x34c, .init(rawValue: 230))
private let __ccc_pair_r: _T1 = (0x34d, .init(rawValue: 220))
private let __ccc_pair_s: _T1 = (0x34e, .init(rawValue: 220))
private let __ccc_pair_t: _T1 = (0x34f, .init(rawValue: 0))
private let __ccc_pair_u: _T1 = (0x350, .init(rawValue: 230))
private let __ccc_pair_v: _T1 = (0x351, .init(rawValue: 230))
private let __ccc_pair_w: _T1 = (0x352, .init(rawValue: 230))
private let __ccc_pair_x: _T1 = (0x353, .init(rawValue: 220))
private let __ccc_pair_y: _T1 = (0x354, .init(rawValue: 220))
private let __ccc_pair_z: _T1 = (0x355, .init(rawValue: 220))
private let __ccc_pair_10: _T1 = (0x356, .init(rawValue: 220))
private let __ccc_pair_11: _T1 = (0x357, .init(rawValue: 230))
private let __ccc_pair_12: _T1 = (0x358, .init(rawValue: 232))
private let __ccc_pair_13: _T1 = (0x359, .init(rawValue: 220))
private let __ccc_pair_14: _T1 = (0x35a, .init(rawValue: 220))
private let __ccc_pair_15: _T1 = (0x35b, .init(rawValue: 230))
private let __ccc_pair_16: _T1 = (0x35c, .init(rawValue: 233))
private let __ccc_pair_17: _T1 = (0x35d, .init(rawValue: 234))
private let __ccc_pair_18: _T1 = (0x35e, .init(rawValue: 234))
private let __ccc_pair_19: _T1 = (0x35f, .init(rawValue: 233))
private let __ccc_pair_1a: _T1 = (0x360, .init(rawValue: 234))
private let __ccc_pair_1b: _T1 = (0x361, .init(rawValue: 234))
private let __ccc_pair_1c: _T1 = (0x362, .init(rawValue: 233))
private let __ccc_pair_1d: _T1 = (0x591, .init(rawValue: 220))
private let __ccc_pair_1e: _T1 = (0x592, .init(rawValue: 230))
private let __ccc_pair_1f: _T1 = (0x593, .init(rawValue: 230))
private let __ccc_pair_1g: _T1 = (0x594, .init(rawValue: 230))
private let __ccc_pair_1h: _T1 = (0x595, .init(rawValue: 230))
private let __ccc_pair_1i: _T1 = (0x596, .init(rawValue: 220))
private let __ccc_pair_1j: _T1 = (0x597, .init(rawValue: 230))
private let __ccc_pair_1k: _T1 = (0x598, .init(rawValue: 230))
private let __ccc_pair_1l: _T1 = (0x599, .init(rawValue: 230))
private let __ccc_pair_1m: _T1 = (0x59a, .init(rawValue: 222))
private let __ccc_pair_1n: _T1 = (0x59b, .init(rawValue: 220))
private let __ccc_pair_1o: _T1 = (0x5a8, .init(rawValue: 230))
private let __ccc_pair_1p: _T1 = (0x5a9, .init(rawValue: 230))
private let __ccc_pair_1q: _T1 = (0x5aa, .init(rawValue: 220))
private let __ccc_pair_1r: _T1 = (0x5ab, .init(rawValue: 230))
private let __ccc_pair_1s: _T1 = (0x5ac, .init(rawValue: 230))
private let __ccc_pair_1t: _T1 = (0x5ad, .init(rawValue: 222))
private let __ccc_pair_1u: _T1 = (0x5ae, .init(rawValue: 228))
private let __ccc_pair_1v: _T1 = (0x5af, .init(rawValue: 230))
private let __ccc_pair_1w: _T1 = (0x5b0, .init(rawValue: 10))
private let __ccc_pair_1x: _T1 = (0x5b1, .init(rawValue: 11))
private let __ccc_pair_1y: _T1 = (0x5b2, .init(rawValue: 12))
private let __ccc_pair_1z: _T1 = (0x5b3, .init(rawValue: 13))
private let __ccc_pair_20: _T1 = (0x5b4, .init(rawValue: 14))
private let __ccc_pair_21: _T1 = (0x5b5, .init(rawValue: 15))
private let __ccc_pair_22: _T1 = (0x5b6, .init(rawValue: 16))
private let __ccc_pair_23: _T1 = (0x5b7, .init(rawValue: 17))
private let __ccc_pair_24: _T1 = (0x5b8, .init(rawValue: 18))
private let __ccc_pair_25: _T1 = (0x5b9, .init(rawValue: 19))
private let __ccc_pair_26: _T1 = (0x5ba, .init(rawValue: 19))
private let __ccc_pair_27: _T1 = (0x5bb, .init(rawValue: 20))
private let __ccc_pair_28: _T1 = (0x5bc, .init(rawValue: 21))
private let __ccc_pair_29: _T1 = (0x5bd, .init(rawValue: 22))
private let __ccc_pair_2a: _T1 = (0x5be, .init(rawValue: 0))
private let __ccc_pair_2b: _T1 = (0x5bf, .init(rawValue: 23))
private let __ccc_pair_2c: _T1 = (0x5c0, .init(rawValue: 0))
private let __ccc_pair_2d: _T1 = (0x5c1, .init(rawValue: 24))
private let __ccc_pair_2e: _T1 = (0x5c2, .init(rawValue: 25))
private let __ccc_pair_2f: _T1 = (0x5c3, .init(rawValue: 0))
private let __ccc_pair_2g: _T1 = (0x5c4, .init(rawValue: 230))
private let __ccc_pair_2h: _T1 = (0x5c5, .init(rawValue: 220))
private let __ccc_pair_2i: _T1 = (0x5c6, .init(rawValue: 0))
private let __ccc_pair_2j: _T1 = (0x5c7, .init(rawValue: 18))
private let __ccc_pair_2k: _T1 = (0x618, .init(rawValue: 30))
private let __ccc_pair_2l: _T1 = (0x619, .init(rawValue: 31))
private let __ccc_pair_2m: _T1 = (0x61a, .init(rawValue: 32))
private let __ccc_pair_2n: _T1 = (0x64b, .init(rawValue: 27))
private let __ccc_pair_2o: _T1 = (0x64c, .init(rawValue: 28))
private let __ccc_pair_2p: _T1 = (0x64d, .init(rawValue: 29))
private let __ccc_pair_2q: _T1 = (0x64e, .init(rawValue: 30))
private let __ccc_pair_2r: _T1 = (0x64f, .init(rawValue: 31))
private let __ccc_pair_2s: _T1 = (0x650, .init(rawValue: 32))
private let __ccc_pair_2t: _T1 = (0x651, .init(rawValue: 33))
private let __ccc_pair_2u: _T1 = (0x652, .init(rawValue: 34))
private let __ccc_pair_2v: _T1 = (0x653, .init(rawValue: 230))
private let __ccc_pair_2w: _T1 = (0x654, .init(rawValue: 230))
private let __ccc_pair_2x: _T1 = (0x655, .init(rawValue: 220))
private let __ccc_pair_2y: _T1 = (0x656, .init(rawValue: 220))
private let __ccc_pair_2z: _T1 = (0x65c, .init(rawValue: 220))
private let __ccc_pair_30: _T1 = (0x65d, .init(rawValue: 230))
private let __ccc_pair_31: _T1 = (0x65e, .init(rawValue: 230))
private let __ccc_pair_32: _T1 = (0x65f, .init(rawValue: 220))
private let __ccc_pair_33: _T1 = (0x670, .init(rawValue: 35))
private let __ccc_pair_34: _T1 = (0x6dd, .init(rawValue: 0))
private let __ccc_pair_35: _T1 = (0x6de, .init(rawValue: 0))
private let __ccc_pair_36: _T1 = (0x6df, .init(rawValue: 230))
private let __ccc_pair_37: _T1 = (0x6e0, .init(rawValue: 230))
private let __ccc_pair_38: _T1 = (0x6e1, .init(rawValue: 230))
private let __ccc_pair_39: _T1 = (0x6e2, .init(rawValue: 230))
private let __ccc_pair_3a: _T1 = (0x6e3, .init(rawValue: 220))
private let __ccc_pair_3b: _T1 = (0x6e4, .init(rawValue: 230))
private let __ccc_pair_3c: _T1 = (0x6e5, .init(rawValue: 0))
private let __ccc_pair_3d: _T1 = (0x6e6, .init(rawValue: 0))
private let __ccc_pair_3e: _T1 = (0x6e7, .init(rawValue: 230))
private let __ccc_pair_3f: _T1 = (0x6e8, .init(rawValue: 230))
private let __ccc_pair_3g: _T1 = (0x6e9, .init(rawValue: 0))
private let __ccc_pair_3h: _T1 = (0x6ea, .init(rawValue: 220))
private let __ccc_pair_3i: _T1 = (0x6eb, .init(rawValue: 230))
private let __ccc_pair_3j: _T1 = (0x6ec, .init(rawValue: 230))
private let __ccc_pair_3k: _T1 = (0x6ed, .init(rawValue: 220))
private let __ccc_pair_3l: _T1 = (0x711, .init(rawValue: 36))
private let __ccc_pair_3m: _T1 = (0x730, .init(rawValue: 230))
private let __ccc_pair_3n: _T1 = (0x731, .init(rawValue: 220))
private let __ccc_pair_3o: _T1 = (0x732, .init(rawValue: 230))
private let __ccc_pair_3p: _T1 = (0x733, .init(rawValue: 230))
private let __ccc_pair_3q: _T1 = (0x734, .init(rawValue: 220))
private let __ccc_pair_3r: _T1 = (0x735, .init(rawValue: 230))
private let __ccc_pair_3s: _T1 = (0x736, .init(rawValue: 230))
private let __ccc_pair_3t: _T1 = (0x737, .init(rawValue: 220))
private let __ccc_pair_3u: _T1 = (0x738, .init(rawValue: 220))
private let __ccc_pair_3v: _T1 = (0x739, .init(rawValue: 220))
private let __ccc_pair_3w: _T1 = (0x73a, .init(rawValue: 230))
private let __ccc_pair_3x: _T1 = (0x73b, .init(rawValue: 220))
private let __ccc_pair_3y: _T1 = (0x73c, .init(rawValue: 220))
private let __ccc_pair_3z: _T1 = (0x73d, .init(rawValue: 230))
private let __ccc_pair_40: _T1 = (0x73e, .init(rawValue: 220))
private let __ccc_pair_41: _T1 = (0x73f, .init(rawValue: 230))
private let __ccc_pair_42: _T1 = (0x740, .init(rawValue: 230))
private let __ccc_pair_43: _T1 = (0x741, .init(rawValue: 230))
private let __ccc_pair_44: _T1 = (0x742, .init(rawValue: 220))
private let __ccc_pair_45: _T1 = (0x743, .init(rawValue: 230))
private let __ccc_pair_46: _T1 = (0x744, .init(rawValue: 220))
private let __ccc_pair_47: _T1 = (0x745, .init(rawValue: 230))
private let __ccc_pair_48: _T1 = (0x746, .init(rawValue: 220))
private let __ccc_pair_49: _T1 = (0x747, .init(rawValue: 230))
private let __ccc_pair_4a: _T1 = (0x748, .init(rawValue: 220))
private let __ccc_pair_4b: _T1 = (0x749, .init(rawValue: 230))
private let __ccc_pair_4c: _T1 = (0x74a, .init(rawValue: 230))
private let __ccc_pair_4d: _T1 = (0x7f2, .init(rawValue: 220))
private let __ccc_pair_4e: _T1 = (0x7f3, .init(rawValue: 230))
private let __ccc_pair_4f: _T1 = (0x7fd, .init(rawValue: 220))
private let __ccc_pair_4g: _T1 = (0x816, .init(rawValue: 230))
private let __ccc_pair_4h: _T1 = (0x817, .init(rawValue: 230))
private let __ccc_pair_4i: _T1 = (0x818, .init(rawValue: 230))
private let __ccc_pair_4j: _T1 = (0x819, .init(rawValue: 230))
private let __ccc_pair_4k: _T1 = (0x81a, .init(rawValue: 0))
private let __ccc_pair_4l: _T1 = (0x824, .init(rawValue: 0))
private let __ccc_pair_4m: _T1 = (0x825, .init(rawValue: 230))
private let __ccc_pair_4n: _T1 = (0x826, .init(rawValue: 230))
private let __ccc_pair_4o: _T1 = (0x827, .init(rawValue: 230))
private let __ccc_pair_4p: _T1 = (0x828, .init(rawValue: 0))
private let __ccc_pair_4q: _T1 = (0x859, .init(rawValue: 220))
private let __ccc_pair_4r: _T1 = (0x85a, .init(rawValue: 220))
private let __ccc_pair_4s: _T1 = (0x85b, .init(rawValue: 220))
private let __ccc_pair_4t: _T1 = (0x8d3, .init(rawValue: 220))
private let __ccc_pair_4u: _T1 = (0x8e2, .init(rawValue: 0))
private let __ccc_pair_4v: _T1 = (0x8e3, .init(rawValue: 220))
private let __ccc_pair_4w: _T1 = (0x8e4, .init(rawValue: 230))
private let __ccc_pair_4x: _T1 = (0x8e5, .init(rawValue: 230))
private let __ccc_pair_4y: _T1 = (0x8e6, .init(rawValue: 220))
private let __ccc_pair_4z: _T1 = (0x8e7, .init(rawValue: 230))
private let __ccc_pair_50: _T1 = (0x8e8, .init(rawValue: 230))
private let __ccc_pair_51: _T1 = (0x8e9, .init(rawValue: 220))
private let __ccc_pair_52: _T1 = (0x8ea, .init(rawValue: 230))
private let __ccc_pair_53: _T1 = (0x8eb, .init(rawValue: 230))
private let __ccc_pair_54: _T1 = (0x8ec, .init(rawValue: 230))
private let __ccc_pair_55: _T1 = (0x8ed, .init(rawValue: 220))
private let __ccc_pair_56: _T1 = (0x8ee, .init(rawValue: 220))
private let __ccc_pair_57: _T1 = (0x8ef, .init(rawValue: 220))
private let __ccc_pair_58: _T1 = (0x8f0, .init(rawValue: 27))
private let __ccc_pair_59: _T1 = (0x8f1, .init(rawValue: 28))
private let __ccc_pair_5a: _T1 = (0x8f2, .init(rawValue: 29))
private let __ccc_pair_5b: _T1 = (0x8f3, .init(rawValue: 230))
private let __ccc_pair_5c: _T1 = (0x8f4, .init(rawValue: 230))
private let __ccc_pair_5d: _T1 = (0x8f5, .init(rawValue: 230))
private let __ccc_pair_5e: _T1 = (0x8f6, .init(rawValue: 220))
private let __ccc_pair_5f: _T1 = (0x8f7, .init(rawValue: 230))
private let __ccc_pair_5g: _T1 = (0x8f8, .init(rawValue: 230))
private let __ccc_pair_5h: _T1 = (0x8f9, .init(rawValue: 220))
private let __ccc_pair_5i: _T1 = (0x8fa, .init(rawValue: 220))
private let __ccc_pair_5j: _T1 = (0x93c, .init(rawValue: 7))
private let __ccc_pair_5k: _T1 = (0x94d, .init(rawValue: 9))
private let __ccc_pair_5l: _T1 = (0x94e, .init(rawValue: 0))
private let __ccc_pair_5m: _T1 = (0x94f, .init(rawValue: 0))
private let __ccc_pair_5n: _T1 = (0x950, .init(rawValue: 0))
private let __ccc_pair_5o: _T1 = (0x951, .init(rawValue: 230))
private let __ccc_pair_5p: _T1 = (0x952, .init(rawValue: 220))
private let __ccc_pair_5q: _T1 = (0x953, .init(rawValue: 230))
private let __ccc_pair_5r: _T1 = (0x954, .init(rawValue: 230))
private let __ccc_pair_5s: _T1 = (0x9bc, .init(rawValue: 7))
private let __ccc_pair_5t: _T1 = (0x9cd, .init(rawValue: 9))
private let __ccc_pair_5u: _T1 = (0x9fe, .init(rawValue: 230))
private let __ccc_pair_5v: _T1 = (0xa3c, .init(rawValue: 7))
private let __ccc_pair_5w: _T1 = (0xa4d, .init(rawValue: 9))
private let __ccc_pair_5x: _T1 = (0xabc, .init(rawValue: 7))
private let __ccc_pair_5y: _T1 = (0xacd, .init(rawValue: 9))
private let __ccc_pair_5z: _T1 = (0xb3c, .init(rawValue: 7))
private let __ccc_pair_60: _T1 = (0xb4d, .init(rawValue: 9))
private let __ccc_pair_61: _T1 = (0xbcd, .init(rawValue: 9))
private let __ccc_pair_62: _T1 = (0xc4d, .init(rawValue: 9))
private let __ccc_pair_63: _T1 = (0xc55, .init(rawValue: 84))
private let __ccc_pair_64: _T1 = (0xc56, .init(rawValue: 91))
private let __ccc_pair_65: _T1 = (0xcbc, .init(rawValue: 7))
private let __ccc_pair_66: _T1 = (0xccd, .init(rawValue: 9))
private let __ccc_pair_67: _T1 = (0xd3b, .init(rawValue: 9))
private let __ccc_pair_68: _T1 = (0xd3c, .init(rawValue: 9))
private let __ccc_pair_69: _T1 = (0xd4d, .init(rawValue: 9))
private let __ccc_pair_6a: _T1 = (0xdca, .init(rawValue: 9))
private let __ccc_pair_6b: _T1 = (0xe38, .init(rawValue: 103))
private let __ccc_pair_6c: _T1 = (0xe39, .init(rawValue: 103))
private let __ccc_pair_6d: _T1 = (0xe3a, .init(rawValue: 9))
private let __ccc_pair_6e: _T1 = (0xe48, .init(rawValue: 107))
private let __ccc_pair_6f: _T1 = (0xe49, .init(rawValue: 107))
private let __ccc_pair_6g: _T1 = (0xe4a, .init(rawValue: 107))
private let __ccc_pair_6h: _T1 = (0xe4b, .init(rawValue: 107))
private let __ccc_pair_6i: _T1 = (0xeb8, .init(rawValue: 118))
private let __ccc_pair_6j: _T1 = (0xeb9, .init(rawValue: 118))
private let __ccc_pair_6k: _T1 = (0xeba, .init(rawValue: 9))
private let __ccc_pair_6l: _T1 = (0xec8, .init(rawValue: 122))
private let __ccc_pair_6m: _T1 = (0xec9, .init(rawValue: 122))
private let __ccc_pair_6n: _T1 = (0xeca, .init(rawValue: 122))
private let __ccc_pair_6o: _T1 = (0xecb, .init(rawValue: 122))
private let __ccc_pair_6p: _T1 = (0xf18, .init(rawValue: 220))
private let __ccc_pair_6q: _T1 = (0xf19, .init(rawValue: 220))
private let __ccc_pair_6r: _T1 = (0xf35, .init(rawValue: 220))
private let __ccc_pair_6s: _T1 = (0xf36, .init(rawValue: 0))
private let __ccc_pair_6t: _T1 = (0xf37, .init(rawValue: 220))
private let __ccc_pair_6u: _T1 = (0xf38, .init(rawValue: 0))
private let __ccc_pair_6v: _T1 = (0xf39, .init(rawValue: 216))
private let __ccc_pair_6w: _T1 = (0xf71, .init(rawValue: 129))
private let __ccc_pair_6x: _T1 = (0xf72, .init(rawValue: 130))
private let __ccc_pair_6y: _T1 = (0xf73, .init(rawValue: 0))
private let __ccc_pair_6z: _T1 = (0xf74, .init(rawValue: 132))
private let __ccc_pair_70: _T1 = (0xf7a, .init(rawValue: 130))
private let __ccc_pair_71: _T1 = (0xf7b, .init(rawValue: 130))
private let __ccc_pair_72: _T1 = (0xf7c, .init(rawValue: 130))
private let __ccc_pair_73: _T1 = (0xf7d, .init(rawValue: 130))
private let __ccc_pair_74: _T1 = (0xf7e, .init(rawValue: 0))
private let __ccc_pair_75: _T1 = (0xf7f, .init(rawValue: 0))
private let __ccc_pair_76: _T1 = (0xf80, .init(rawValue: 130))
private let __ccc_pair_77: _T1 = (0xf81, .init(rawValue: 0))
private let __ccc_pair_78: _T1 = (0xf82, .init(rawValue: 230))
private let __ccc_pair_79: _T1 = (0xf83, .init(rawValue: 230))
private let __ccc_pair_7a: _T1 = (0xf84, .init(rawValue: 9))
private let __ccc_pair_7b: _T1 = (0xf85, .init(rawValue: 0))
private let __ccc_pair_7c: _T1 = (0xf86, .init(rawValue: 230))
private let __ccc_pair_7d: _T1 = (0xf87, .init(rawValue: 230))
private let __ccc_pair_7e: _T1 = (0xfc6, .init(rawValue: 220))
private let __ccc_pair_7f: _T1 = (0x1037, .init(rawValue: 7))
private let __ccc_pair_7g: _T1 = (0x1038, .init(rawValue: 0))
private let __ccc_pair_7h: _T1 = (0x1039, .init(rawValue: 9))
private let __ccc_pair_7i: _T1 = (0x103a, .init(rawValue: 9))
private let __ccc_pair_7j: _T1 = (0x108d, .init(rawValue: 220))
private let __ccc_pair_7k: _T1 = (0x135d, .init(rawValue: 230))
private let __ccc_pair_7l: _T1 = (0x135e, .init(rawValue: 230))
private let __ccc_pair_7m: _T1 = (0x135f, .init(rawValue: 230))
private let __ccc_pair_7n: _T1 = (0x1714, .init(rawValue: 9))
private let __ccc_pair_7o: _T1 = (0x1734, .init(rawValue: 9))
private let __ccc_pair_7p: _T1 = (0x17d2, .init(rawValue: 9))
private let __ccc_pair_7q: _T1 = (0x17dd, .init(rawValue: 230))
private let __ccc_pair_7r: _T1 = (0x18a9, .init(rawValue: 228))
private let __ccc_pair_7s: _T1 = (0x1939, .init(rawValue: 222))
private let __ccc_pair_7t: _T1 = (0x193a, .init(rawValue: 230))
private let __ccc_pair_7u: _T1 = (0x193b, .init(rawValue: 220))
private let __ccc_pair_7v: _T1 = (0x1a17, .init(rawValue: 230))
private let __ccc_pair_7w: _T1 = (0x1a18, .init(rawValue: 220))
private let __ccc_pair_7x: _T1 = (0x1a60, .init(rawValue: 9))
private let __ccc_pair_7y: _T1 = (0x1a7d, .init(rawValue: 0))
private let __ccc_pair_7z: _T1 = (0x1a7e, .init(rawValue: 0))
private let __ccc_pair_80: _T1 = (0x1a7f, .init(rawValue: 220))
private let __ccc_pair_81: _T1 = (0x1abb, .init(rawValue: 230))
private let __ccc_pair_82: _T1 = (0x1abc, .init(rawValue: 230))
private let __ccc_pair_83: _T1 = (0x1abd, .init(rawValue: 220))
private let __ccc_pair_84: _T1 = (0x1b34, .init(rawValue: 7))
private let __ccc_pair_85: _T1 = (0x1b44, .init(rawValue: 9))
private let __ccc_pair_86: _T1 = (0x1b6b, .init(rawValue: 230))
private let __ccc_pair_87: _T1 = (0x1b6c, .init(rawValue: 220))
private let __ccc_pair_88: _T1 = (0x1baa, .init(rawValue: 9))
private let __ccc_pair_89: _T1 = (0x1bab, .init(rawValue: 9))
private let __ccc_pair_8a: _T1 = (0x1be6, .init(rawValue: 7))
private let __ccc_pair_8b: _T1 = (0x1bf2, .init(rawValue: 9))
private let __ccc_pair_8c: _T1 = (0x1bf3, .init(rawValue: 9))
private let __ccc_pair_8d: _T1 = (0x1c37, .init(rawValue: 7))
private let __ccc_pair_8e: _T1 = (0x1cd0, .init(rawValue: 230))
private let __ccc_pair_8f: _T1 = (0x1cd1, .init(rawValue: 230))
private let __ccc_pair_8g: _T1 = (0x1cd2, .init(rawValue: 230))
private let __ccc_pair_8h: _T1 = (0x1cd3, .init(rawValue: 0))
private let __ccc_pair_8i: _T1 = (0x1cd4, .init(rawValue: 1))
private let __ccc_pair_8j: _T1 = (0x1cda, .init(rawValue: 230))
private let __ccc_pair_8k: _T1 = (0x1cdb, .init(rawValue: 230))
private let __ccc_pair_8l: _T1 = (0x1cdc, .init(rawValue: 220))
private let __ccc_pair_8m: _T1 = (0x1cdd, .init(rawValue: 220))
private let __ccc_pair_8n: _T1 = (0x1cde, .init(rawValue: 220))
private let __ccc_pair_8o: _T1 = (0x1cdf, .init(rawValue: 220))
private let __ccc_pair_8p: _T1 = (0x1ce0, .init(rawValue: 230))
private let __ccc_pair_8q: _T1 = (0x1ce1, .init(rawValue: 0))
private let __ccc_pair_8r: _T1 = (0x1ce9, .init(rawValue: 0))
private let __ccc_pair_8s: _T1 = (0x1cea, .init(rawValue: 0))
private let __ccc_pair_8t: _T1 = (0x1ceb, .init(rawValue: 0))
private let __ccc_pair_8u: _T1 = (0x1cec, .init(rawValue: 0))
private let __ccc_pair_8v: _T1 = (0x1ced, .init(rawValue: 220))
private let __ccc_pair_8w: _T1 = (0x1cf4, .init(rawValue: 230))
private let __ccc_pair_8x: _T1 = (0x1cf5, .init(rawValue: 0))
private let __ccc_pair_8y: _T1 = (0x1cf6, .init(rawValue: 0))
private let __ccc_pair_8z: _T1 = (0x1cf7, .init(rawValue: 0))
private let __ccc_pair_90: _T1 = (0x1cf8, .init(rawValue: 230))
private let __ccc_pair_91: _T1 = (0x1cf9, .init(rawValue: 230))
private let __ccc_pair_92: _T1 = (0x1dc0, .init(rawValue: 230))
private let __ccc_pair_93: _T1 = (0x1dc1, .init(rawValue: 230))
private let __ccc_pair_94: _T1 = (0x1dc2, .init(rawValue: 220))
private let __ccc_pair_95: _T1 = (0x1dca, .init(rawValue: 220))
private let __ccc_pair_96: _T1 = (0x1dcb, .init(rawValue: 230))
private let __ccc_pair_97: _T1 = (0x1dcc, .init(rawValue: 230))
private let __ccc_pair_98: _T1 = (0x1dcd, .init(rawValue: 234))
private let __ccc_pair_99: _T1 = (0x1dce, .init(rawValue: 214))
private let __ccc_pair_9a: _T1 = (0x1dcf, .init(rawValue: 220))
private let __ccc_pair_9b: _T1 = (0x1dd0, .init(rawValue: 202))
private let __ccc_pair_9c: _T1 = (0x1df6, .init(rawValue: 232))
private let __ccc_pair_9d: _T1 = (0x1df7, .init(rawValue: 228))
private let __ccc_pair_9e: _T1 = (0x1df8, .init(rawValue: 228))
private let __ccc_pair_9f: _T1 = (0x1df9, .init(rawValue: 220))
private let __ccc_pair_9g: _T1 = (0x1dfa, .init(rawValue: 0))
private let __ccc_pair_9h: _T1 = (0x1dfb, .init(rawValue: 230))
private let __ccc_pair_9i: _T1 = (0x1dfc, .init(rawValue: 233))
private let __ccc_pair_9j: _T1 = (0x1dfd, .init(rawValue: 220))
private let __ccc_pair_9k: _T1 = (0x1dfe, .init(rawValue: 230))
private let __ccc_pair_9l: _T1 = (0x1dff, .init(rawValue: 220))
private let __ccc_pair_9m: _T1 = (0x20d0, .init(rawValue: 230))
private let __ccc_pair_9n: _T1 = (0x20d1, .init(rawValue: 230))
private let __ccc_pair_9o: _T1 = (0x20d2, .init(rawValue: 1))
private let __ccc_pair_9p: _T1 = (0x20d3, .init(rawValue: 1))
private let __ccc_pair_9q: _T1 = (0x20d4, .init(rawValue: 230))
private let __ccc_pair_9r: _T1 = (0x20d5, .init(rawValue: 230))
private let __ccc_pair_9s: _T1 = (0x20d6, .init(rawValue: 230))
private let __ccc_pair_9t: _T1 = (0x20d7, .init(rawValue: 230))
private let __ccc_pair_9u: _T1 = (0x20d8, .init(rawValue: 1))
private let __ccc_pair_9v: _T1 = (0x20d9, .init(rawValue: 1))
private let __ccc_pair_9w: _T1 = (0x20da, .init(rawValue: 1))
private let __ccc_pair_9x: _T1 = (0x20db, .init(rawValue: 230))
private let __ccc_pair_9y: _T1 = (0x20dc, .init(rawValue: 230))
private let __ccc_pair_9z: _T1 = (0x20dd, .init(rawValue: 0))
private let __ccc_pair_a0: _T1 = (0x20de, .init(rawValue: 0))
private let __ccc_pair_a1: _T1 = (0x20df, .init(rawValue: 0))
private let __ccc_pair_a2: _T1 = (0x20e0, .init(rawValue: 0))
private let __ccc_pair_a3: _T1 = (0x20e1, .init(rawValue: 230))
private let __ccc_pair_a4: _T1 = (0x20e2, .init(rawValue: 0))
private let __ccc_pair_a5: _T1 = (0x20e3, .init(rawValue: 0))
private let __ccc_pair_a6: _T1 = (0x20e4, .init(rawValue: 0))
private let __ccc_pair_a7: _T1 = (0x20e5, .init(rawValue: 1))
private let __ccc_pair_a8: _T1 = (0x20e6, .init(rawValue: 1))
private let __ccc_pair_a9: _T1 = (0x20e7, .init(rawValue: 230))
private let __ccc_pair_aa: _T1 = (0x20e8, .init(rawValue: 220))
private let __ccc_pair_ab: _T1 = (0x20e9, .init(rawValue: 230))
private let __ccc_pair_ac: _T1 = (0x20ea, .init(rawValue: 1))
private let __ccc_pair_ad: _T1 = (0x20eb, .init(rawValue: 1))
private let __ccc_pair_ae: _T1 = (0x20ec, .init(rawValue: 220))
private let __ccc_pair_af: _T1 = (0x20ed, .init(rawValue: 220))
private let __ccc_pair_ag: _T1 = (0x20ee, .init(rawValue: 220))
private let __ccc_pair_ah: _T1 = (0x20ef, .init(rawValue: 220))
private let __ccc_pair_ai: _T1 = (0x20f0, .init(rawValue: 230))
private let __ccc_pair_aj: _T1 = (0x2cef, .init(rawValue: 230))
private let __ccc_pair_ak: _T1 = (0x2cf0, .init(rawValue: 230))
private let __ccc_pair_al: _T1 = (0x2cf1, .init(rawValue: 230))
private let __ccc_pair_am: _T1 = (0x2d7f, .init(rawValue: 9))
private let __ccc_pair_an: _T1 = (0x302a, .init(rawValue: 218))
private let __ccc_pair_ao: _T1 = (0x302b, .init(rawValue: 228))
private let __ccc_pair_ap: _T1 = (0x302c, .init(rawValue: 232))
private let __ccc_pair_aq: _T1 = (0x302d, .init(rawValue: 222))
private let __ccc_pair_ar: _T1 = (0x302e, .init(rawValue: 224))
private let __ccc_pair_as: _T1 = (0x302f, .init(rawValue: 224))
private let __ccc_pair_at: _T1 = (0x3099, .init(rawValue: 8))
private let __ccc_pair_au: _T1 = (0x309a, .init(rawValue: 8))
private let __ccc_pair_av: _T1 = (0xa66f, .init(rawValue: 230))
private let __ccc_pair_aw: _T1 = (0xa670, .init(rawValue: 0))
private let __ccc_pair_ax: _T1 = (0xa671, .init(rawValue: 0))
private let __ccc_pair_ay: _T1 = (0xa672, .init(rawValue: 0))
private let __ccc_pair_az: _T1 = (0xa673, .init(rawValue: 0))
private let __ccc_pair_b0: _T1 = (0xa69e, .init(rawValue: 230))
private let __ccc_pair_b1: _T1 = (0xa69f, .init(rawValue: 230))
private let __ccc_pair_b2: _T1 = (0xa6f0, .init(rawValue: 230))
private let __ccc_pair_b3: _T1 = (0xa6f1, .init(rawValue: 230))
private let __ccc_pair_b4: _T1 = (0xa806, .init(rawValue: 9))
private let __ccc_pair_b5: _T1 = (0xa8c4, .init(rawValue: 9))
private let __ccc_pair_b6: _T1 = (0xa92b, .init(rawValue: 220))
private let __ccc_pair_b7: _T1 = (0xa92c, .init(rawValue: 220))
private let __ccc_pair_b8: _T1 = (0xa92d, .init(rawValue: 220))
private let __ccc_pair_b9: _T1 = (0xa953, .init(rawValue: 9))
private let __ccc_pair_ba: _T1 = (0xa9b3, .init(rawValue: 7))
private let __ccc_pair_bb: _T1 = (0xa9c0, .init(rawValue: 9))
private let __ccc_pair_bc: _T1 = (0xaab0, .init(rawValue: 230))
private let __ccc_pair_bd: _T1 = (0xaab1, .init(rawValue: 0))
private let __ccc_pair_be: _T1 = (0xaab2, .init(rawValue: 230))
private let __ccc_pair_bf: _T1 = (0xaab3, .init(rawValue: 230))
private let __ccc_pair_bg: _T1 = (0xaab4, .init(rawValue: 220))
private let __ccc_pair_bh: _T1 = (0xaab5, .init(rawValue: 0))
private let __ccc_pair_bi: _T1 = (0xaab6, .init(rawValue: 0))
private let __ccc_pair_bj: _T1 = (0xaab7, .init(rawValue: 230))
private let __ccc_pair_bk: _T1 = (0xaab8, .init(rawValue: 230))
private let __ccc_pair_bl: _T1 = (0xaabe, .init(rawValue: 230))
private let __ccc_pair_bm: _T1 = (0xaabf, .init(rawValue: 230))
private let __ccc_pair_bn: _T1 = (0xaac0, .init(rawValue: 0))
private let __ccc_pair_bo: _T1 = (0xaac1, .init(rawValue: 230))
private let __ccc_pair_bp: _T1 = (0xaaf6, .init(rawValue: 9))
private let __ccc_pair_bq: _T1 = (0xabed, .init(rawValue: 9))
private let __ccc_pair_br: _T1 = (0xfb1e, .init(rawValue: 26))
private let __ccc_pair_bs: _T1 = (0xfe2e, .init(rawValue: 230))
private let __ccc_pair_bt: _T1 = (0xfe2f, .init(rawValue: 230))
private let __ccc_pair_bu: _T1 = (0x101fd, .init(rawValue: 220))
private let __ccc_pair_bv: _T1 = (0x102e0, .init(rawValue: 220))
private let __ccc_pair_bw: _T1 = (0x10a0d, .init(rawValue: 220))
private let __ccc_pair_bx: _T1 = (0x10a0e, .init(rawValue: 0))
private let __ccc_pair_by: _T1 = (0x10a0f, .init(rawValue: 230))
private let __ccc_pair_bz: _T1 = (0x10a38, .init(rawValue: 230))
private let __ccc_pair_c0: _T1 = (0x10a39, .init(rawValue: 1))
private let __ccc_pair_c1: _T1 = (0x10a3a, .init(rawValue: 220))
private let __ccc_pair_c2: _T1 = (0x10a3b, .init(rawValue: 0))
private let __ccc_pair_c3: _T1 = (0x10a3c, .init(rawValue: 0))
private let __ccc_pair_c4: _T1 = (0x10a3d, .init(rawValue: 0))
private let __ccc_pair_c5: _T1 = (0x10a3e, .init(rawValue: 0))
private let __ccc_pair_c6: _T1 = (0x10a3f, .init(rawValue: 9))
private let __ccc_pair_c7: _T1 = (0x10ae5, .init(rawValue: 230))
private let __ccc_pair_c8: _T1 = (0x10ae6, .init(rawValue: 220))
private let __ccc_pair_c9: _T1 = (0x10d24, .init(rawValue: 230))
private let __ccc_pair_ca: _T1 = (0x10d25, .init(rawValue: 230))
private let __ccc_pair_cb: _T1 = (0x10d26, .init(rawValue: 230))
private let __ccc_pair_cc: _T1 = (0x10d27, .init(rawValue: 230))
private let __ccc_pair_cd: _T1 = (0x10f46, .init(rawValue: 220))
private let __ccc_pair_ce: _T1 = (0x10f47, .init(rawValue: 220))
private let __ccc_pair_cf: _T1 = (0x10f48, .init(rawValue: 230))
private let __ccc_pair_cg: _T1 = (0x10f49, .init(rawValue: 230))
private let __ccc_pair_ch: _T1 = (0x10f4a, .init(rawValue: 230))
private let __ccc_pair_ci: _T1 = (0x10f4b, .init(rawValue: 220))
private let __ccc_pair_cj: _T1 = (0x10f4c, .init(rawValue: 230))
private let __ccc_pair_ck: _T1 = (0x10f4d, .init(rawValue: 220))
private let __ccc_pair_cl: _T1 = (0x10f4e, .init(rawValue: 220))
private let __ccc_pair_cm: _T1 = (0x10f4f, .init(rawValue: 220))
private let __ccc_pair_cn: _T1 = (0x10f50, .init(rawValue: 220))
private let __ccc_pair_co: _T1 = (0x11046, .init(rawValue: 9))
private let __ccc_pair_cp: _T1 = (0x1107f, .init(rawValue: 9))
private let __ccc_pair_cq: _T1 = (0x110b9, .init(rawValue: 9))
private let __ccc_pair_cr: _T1 = (0x110ba, .init(rawValue: 7))
private let __ccc_pair_cs: _T1 = (0x11100, .init(rawValue: 230))
private let __ccc_pair_ct: _T1 = (0x11101, .init(rawValue: 230))
private let __ccc_pair_cu: _T1 = (0x11102, .init(rawValue: 230))
private let __ccc_pair_cv: _T1 = (0x11133, .init(rawValue: 9))
private let __ccc_pair_cw: _T1 = (0x11134, .init(rawValue: 9))
private let __ccc_pair_cx: _T1 = (0x11173, .init(rawValue: 7))
private let __ccc_pair_cy: _T1 = (0x111c0, .init(rawValue: 9))
private let __ccc_pair_cz: _T1 = (0x111ca, .init(rawValue: 7))
private let __ccc_pair_d0: _T1 = (0x11235, .init(rawValue: 9))
private let __ccc_pair_d1: _T1 = (0x11236, .init(rawValue: 7))
private let __ccc_pair_d2: _T1 = (0x112e9, .init(rawValue: 7))
private let __ccc_pair_d3: _T1 = (0x112ea, .init(rawValue: 9))
private let __ccc_pair_d4: _T1 = (0x1133b, .init(rawValue: 7))
private let __ccc_pair_d5: _T1 = (0x1133c, .init(rawValue: 7))
private let __ccc_pair_d6: _T1 = (0x1134d, .init(rawValue: 9))
private let __ccc_pair_d7: _T1 = (0x1136d, .init(rawValue: 0))
private let __ccc_pair_d8: _T1 = (0x1136e, .init(rawValue: 0))
private let __ccc_pair_d9: _T1 = (0x1136f, .init(rawValue: 0))
private let __ccc_pair_da: _T1 = (0x11442, .init(rawValue: 9))
private let __ccc_pair_db: _T1 = (0x11443, .init(rawValue: 0))
private let __ccc_pair_dc: _T1 = (0x11444, .init(rawValue: 0))
private let __ccc_pair_dd: _T1 = (0x11445, .init(rawValue: 0))
private let __ccc_pair_de: _T1 = (0x11446, .init(rawValue: 7))
private let __ccc_pair_df: _T1 = (0x1145e, .init(rawValue: 230))
private let __ccc_pair_dg: _T1 = (0x114c2, .init(rawValue: 9))
private let __ccc_pair_dh: _T1 = (0x114c3, .init(rawValue: 7))
private let __ccc_pair_di: _T1 = (0x115bf, .init(rawValue: 9))
private let __ccc_pair_dj: _T1 = (0x115c0, .init(rawValue: 7))
private let __ccc_pair_dk: _T1 = (0x1163f, .init(rawValue: 9))
private let __ccc_pair_dl: _T1 = (0x116b6, .init(rawValue: 9))
private let __ccc_pair_dm: _T1 = (0x116b7, .init(rawValue: 7))
private let __ccc_pair_dn: _T1 = (0x1172b, .init(rawValue: 9))
private let __ccc_pair_do: _T1 = (0x11839, .init(rawValue: 9))
private let __ccc_pair_dp: _T1 = (0x1183a, .init(rawValue: 7))
private let __ccc_pair_dq: _T1 = (0x119e0, .init(rawValue: 9))
private let __ccc_pair_dr: _T1 = (0x11a34, .init(rawValue: 9))
private let __ccc_pair_ds: _T1 = (0x11a47, .init(rawValue: 9))
private let __ccc_pair_dt: _T1 = (0x11a99, .init(rawValue: 9))
private let __ccc_pair_du: _T1 = (0x11c3f, .init(rawValue: 9))
private let __ccc_pair_dv: _T1 = (0x11d42, .init(rawValue: 7))
private let __ccc_pair_dw: _T1 = (0x11d43, .init(rawValue: 0))
private let __ccc_pair_dx: _T1 = (0x11d44, .init(rawValue: 9))
private let __ccc_pair_dy: _T1 = (0x11d45, .init(rawValue: 9))
private let __ccc_pair_dz: _T1 = (0x11d97, .init(rawValue: 9))
private let __ccc_pair_e0: _T1 = (0x1bc9e, .init(rawValue: 1))
private let __ccc_pair_e1: _T1 = (0x1d165, .init(rawValue: 216))
private let __ccc_pair_e2: _T1 = (0x1d166, .init(rawValue: 216))
private let __ccc_pair_e3: _T1 = (0x1d167, .init(rawValue: 1))
private let __ccc_pair_e4: _T1 = (0x1d168, .init(rawValue: 1))
private let __ccc_pair_e5: _T1 = (0x1d169, .init(rawValue: 1))
private let __ccc_pair_e6: _T1 = (0x1d16a, .init(rawValue: 0))
private let __ccc_pair_e7: _T1 = (0x1d16b, .init(rawValue: 0))
private let __ccc_pair_e8: _T1 = (0x1d16c, .init(rawValue: 0))
private let __ccc_pair_e9: _T1 = (0x1d16d, .init(rawValue: 226))
private let __ccc_pair_ea: _T1 = (0x1d183, .init(rawValue: 0))
private let __ccc_pair_eb: _T1 = (0x1d184, .init(rawValue: 0))
private let __ccc_pair_ec: _T1 = (0x1d18a, .init(rawValue: 220))
private let __ccc_pair_ed: _T1 = (0x1d18b, .init(rawValue: 220))
private let __ccc_pair_ee: _T1 = (0x1d1aa, .init(rawValue: 230))
private let __ccc_pair_ef: _T1 = (0x1d1ab, .init(rawValue: 230))
private let __ccc_pair_eg: _T1 = (0x1d1ac, .init(rawValue: 230))
private let __ccc_pair_eh: _T1 = (0x1d1ad, .init(rawValue: 230))
private let __ccc_pair_ei: _T1 = (0x1d242, .init(rawValue: 230))
private let __ccc_pair_ej: _T1 = (0x1d243, .init(rawValue: 230))
private let __ccc_pair_ek: _T1 = (0x1d244, .init(rawValue: 230))
private let __ccc_pair_el: _T1 = (0x1e007, .init(rawValue: 0))
private let __ccc_pair_em: _T1 = (0x1e019, .init(rawValue: 0))
private let __ccc_pair_en: _T1 = (0x1e01a, .init(rawValue: 0))
private let __ccc_pair_eo: _T1 = (0x1e022, .init(rawValue: 0))
private let __ccc_pair_ep: _T1 = (0x1e023, .init(rawValue: 230))
private let __ccc_pair_eq: _T1 = (0x1e024, .init(rawValue: 230))
private let __ccc_pair_er: _T1 = (0x1e025, .init(rawValue: 0))
private let __ccc_pair_es: _T1 = (0x1e2ec, .init(rawValue: 230))
private let __ccc_pair_et: _T1 = (0x1e2ed, .init(rawValue: 230))
private let __ccc_pair_eu: _T1 = (0x1e2ee, .init(rawValue: 230))
private let __ccc_pair_ev: _T1 = (0x1e2ef, .init(rawValue: 230))
private let __ccc_pair_ew: _T1 = (0x1e94a, .init(rawValue: 7))
private let __ccc_dictionary = Dictionary<Unicode.Scalar.Value, _T0>(uniqueKeysWithValues: [
  __ccc_pair_0,
  __ccc_pair_1,
  __ccc_pair_2,
  __ccc_pair_3,
  __ccc_pair_4,
  __ccc_pair_5,
  __ccc_pair_6,
  __ccc_pair_7,
  __ccc_pair_8,
  __ccc_pair_9,
  __ccc_pair_a,
  __ccc_pair_b,
  __ccc_pair_c,
  __ccc_pair_d,
  __ccc_pair_e,
  __ccc_pair_f,
  __ccc_pair_g,
  __ccc_pair_h,
  __ccc_pair_i,
  __ccc_pair_j,
  __ccc_pair_k,
  __ccc_pair_l,
  __ccc_pair_m,
  __ccc_pair_n,
  __ccc_pair_o,
  __ccc_pair_p,
  __ccc_pair_q,
  __ccc_pair_r,
  __ccc_pair_s,
  __ccc_pair_t,
  __ccc_pair_u,
  __ccc_pair_v,
  __ccc_pair_w,
  __ccc_pair_x,
  __ccc_pair_y,
  __ccc_pair_z,
  __ccc_pair_10,
  __ccc_pair_11,
  __ccc_pair_12,
  __ccc_pair_13,
  __ccc_pair_14,
  __ccc_pair_15,
  __ccc_pair_16,
  __ccc_pair_17,
  __ccc_pair_18,
  __ccc_pair_19,
  __ccc_pair_1a,
  __ccc_pair_1b,
  __ccc_pair_1c,
  __ccc_pair_1d,
  __ccc_pair_1e,
  __ccc_pair_1f,
  __ccc_pair_1g,
  __ccc_pair_1h,
  __ccc_pair_1i,
  __ccc_pair_1j,
  __ccc_pair_1k,
  __ccc_pair_1l,
  __ccc_pair_1m,
  __ccc_pair_1n,
  __ccc_pair_1o,
  __ccc_pair_1p,
  __ccc_pair_1q,
  __ccc_pair_1r,
  __ccc_pair_1s,
  __ccc_pair_1t,
  __ccc_pair_1u,
  __ccc_pair_1v,
  __ccc_pair_1w,
  __ccc_pair_1x,
  __ccc_pair_1y,
  __ccc_pair_1z,
  __ccc_pair_20,
  __ccc_pair_21,
  __ccc_pair_22,
  __ccc_pair_23,
  __ccc_pair_24,
  __ccc_pair_25,
  __ccc_pair_26,
  __ccc_pair_27,
  __ccc_pair_28,
  __ccc_pair_29,
  __ccc_pair_2a,
  __ccc_pair_2b,
  __ccc_pair_2c,
  __ccc_pair_2d,
  __ccc_pair_2e,
  __ccc_pair_2f,
  __ccc_pair_2g,
  __ccc_pair_2h,
  __ccc_pair_2i,
  __ccc_pair_2j,
  __ccc_pair_2k,
  __ccc_pair_2l,
  __ccc_pair_2m,
  __ccc_pair_2n,
  __ccc_pair_2o,
  __ccc_pair_2p,
  __ccc_pair_2q,
  __ccc_pair_2r,
  __ccc_pair_2s,
  __ccc_pair_2t,
  __ccc_pair_2u,
  __ccc_pair_2v,
  __ccc_pair_2w,
  __ccc_pair_2x,
  __ccc_pair_2y,
  __ccc_pair_2z,
  __ccc_pair_30,
  __ccc_pair_31,
  __ccc_pair_32,
  __ccc_pair_33,
  __ccc_pair_34,
  __ccc_pair_35,
  __ccc_pair_36,
  __ccc_pair_37,
  __ccc_pair_38,
  __ccc_pair_39,
  __ccc_pair_3a,
  __ccc_pair_3b,
  __ccc_pair_3c,
  __ccc_pair_3d,
  __ccc_pair_3e,
  __ccc_pair_3f,
  __ccc_pair_3g,
  __ccc_pair_3h,
  __ccc_pair_3i,
  __ccc_pair_3j,
  __ccc_pair_3k,
  __ccc_pair_3l,
  __ccc_pair_3m,
  __ccc_pair_3n,
  __ccc_pair_3o,
  __ccc_pair_3p,
  __ccc_pair_3q,
  __ccc_pair_3r,
  __ccc_pair_3s,
  __ccc_pair_3t,
  __ccc_pair_3u,
  __ccc_pair_3v,
  __ccc_pair_3w,
  __ccc_pair_3x,
  __ccc_pair_3y,
  __ccc_pair_3z,
  __ccc_pair_40,
  __ccc_pair_41,
  __ccc_pair_42,
  __ccc_pair_43,
  __ccc_pair_44,
  __ccc_pair_45,
  __ccc_pair_46,
  __ccc_pair_47,
  __ccc_pair_48,
  __ccc_pair_49,
  __ccc_pair_4a,
  __ccc_pair_4b,
  __ccc_pair_4c,
  __ccc_pair_4d,
  __ccc_pair_4e,
  __ccc_pair_4f,
  __ccc_pair_4g,
  __ccc_pair_4h,
  __ccc_pair_4i,
  __ccc_pair_4j,
  __ccc_pair_4k,
  __ccc_pair_4l,
  __ccc_pair_4m,
  __ccc_pair_4n,
  __ccc_pair_4o,
  __ccc_pair_4p,
  __ccc_pair_4q,
  __ccc_pair_4r,
  __ccc_pair_4s,
  __ccc_pair_4t,
  __ccc_pair_4u,
  __ccc_pair_4v,
  __ccc_pair_4w,
  __ccc_pair_4x,
  __ccc_pair_4y,
  __ccc_pair_4z,
  __ccc_pair_50,
  __ccc_pair_51,
  __ccc_pair_52,
  __ccc_pair_53,
  __ccc_pair_54,
  __ccc_pair_55,
  __ccc_pair_56,
  __ccc_pair_57,
  __ccc_pair_58,
  __ccc_pair_59,
  __ccc_pair_5a,
  __ccc_pair_5b,
  __ccc_pair_5c,
  __ccc_pair_5d,
  __ccc_pair_5e,
  __ccc_pair_5f,
  __ccc_pair_5g,
  __ccc_pair_5h,
  __ccc_pair_5i,
  __ccc_pair_5j,
  __ccc_pair_5k,
  __ccc_pair_5l,
  __ccc_pair_5m,
  __ccc_pair_5n,
  __ccc_pair_5o,
  __ccc_pair_5p,
  __ccc_pair_5q,
  __ccc_pair_5r,
  __ccc_pair_5s,
  __ccc_pair_5t,
  __ccc_pair_5u,
  __ccc_pair_5v,
  __ccc_pair_5w,
  __ccc_pair_5x,
  __ccc_pair_5y,
  __ccc_pair_5z,
  __ccc_pair_60,
  __ccc_pair_61,
  __ccc_pair_62,
  __ccc_pair_63,
  __ccc_pair_64,
  __ccc_pair_65,
  __ccc_pair_66,
  __ccc_pair_67,
  __ccc_pair_68,
  __ccc_pair_69,
  __ccc_pair_6a,
  __ccc_pair_6b,
  __ccc_pair_6c,
  __ccc_pair_6d,
  __ccc_pair_6e,
  __ccc_pair_6f,
  __ccc_pair_6g,
  __ccc_pair_6h,
  __ccc_pair_6i,
  __ccc_pair_6j,
  __ccc_pair_6k,
  __ccc_pair_6l,
  __ccc_pair_6m,
  __ccc_pair_6n,
  __ccc_pair_6o,
  __ccc_pair_6p,
  __ccc_pair_6q,
  __ccc_pair_6r,
  __ccc_pair_6s,
  __ccc_pair_6t,
  __ccc_pair_6u,
  __ccc_pair_6v,
  __ccc_pair_6w,
  __ccc_pair_6x,
  __ccc_pair_6y,
  __ccc_pair_6z,
  __ccc_pair_70,
  __ccc_pair_71,
  __ccc_pair_72,
  __ccc_pair_73,
  __ccc_pair_74,
  __ccc_pair_75,
  __ccc_pair_76,
  __ccc_pair_77,
  __ccc_pair_78,
  __ccc_pair_79,
  __ccc_pair_7a,
  __ccc_pair_7b,
  __ccc_pair_7c,
  __ccc_pair_7d,
  __ccc_pair_7e,
  __ccc_pair_7f,
  __ccc_pair_7g,
  __ccc_pair_7h,
  __ccc_pair_7i,
  __ccc_pair_7j,
  __ccc_pair_7k,
  __ccc_pair_7l,
  __ccc_pair_7m,
  __ccc_pair_7n,
  __ccc_pair_7o,
  __ccc_pair_7p,
  __ccc_pair_7q,
  __ccc_pair_7r,
  __ccc_pair_7s,
  __ccc_pair_7t,
  __ccc_pair_7u,
  __ccc_pair_7v,
  __ccc_pair_7w,
  __ccc_pair_7x,
  __ccc_pair_7y,
  __ccc_pair_7z,
  __ccc_pair_80,
  __ccc_pair_81,
  __ccc_pair_82,
  __ccc_pair_83,
  __ccc_pair_84,
  __ccc_pair_85,
  __ccc_pair_86,
  __ccc_pair_87,
  __ccc_pair_88,
  __ccc_pair_89,
  __ccc_pair_8a,
  __ccc_pair_8b,
  __ccc_pair_8c,
  __ccc_pair_8d,
  __ccc_pair_8e,
  __ccc_pair_8f,
  __ccc_pair_8g,
  __ccc_pair_8h,
  __ccc_pair_8i,
  __ccc_pair_8j,
  __ccc_pair_8k,
  __ccc_pair_8l,
  __ccc_pair_8m,
  __ccc_pair_8n,
  __ccc_pair_8o,
  __ccc_pair_8p,
  __ccc_pair_8q,
  __ccc_pair_8r,
  __ccc_pair_8s,
  __ccc_pair_8t,
  __ccc_pair_8u,
  __ccc_pair_8v,
  __ccc_pair_8w,
  __ccc_pair_8x,
  __ccc_pair_8y,
  __ccc_pair_8z,
  __ccc_pair_90,
  __ccc_pair_91,
  __ccc_pair_92,
  __ccc_pair_93,
  __ccc_pair_94,
  __ccc_pair_95,
  __ccc_pair_96,
  __ccc_pair_97,
  __ccc_pair_98,
  __ccc_pair_99,
  __ccc_pair_9a,
  __ccc_pair_9b,
  __ccc_pair_9c,
  __ccc_pair_9d,
  __ccc_pair_9e,
  __ccc_pair_9f,
  __ccc_pair_9g,
  __ccc_pair_9h,
  __ccc_pair_9i,
  __ccc_pair_9j,
  __ccc_pair_9k,
  __ccc_pair_9l,
  __ccc_pair_9m,
  __ccc_pair_9n,
  __ccc_pair_9o,
  __ccc_pair_9p,
  __ccc_pair_9q,
  __ccc_pair_9r,
  __ccc_pair_9s,
  __ccc_pair_9t,
  __ccc_pair_9u,
  __ccc_pair_9v,
  __ccc_pair_9w,
  __ccc_pair_9x,
  __ccc_pair_9y,
  __ccc_pair_9z,
  __ccc_pair_a0,
  __ccc_pair_a1,
  __ccc_pair_a2,
  __ccc_pair_a3,
  __ccc_pair_a4,
  __ccc_pair_a5,
  __ccc_pair_a6,
  __ccc_pair_a7,
  __ccc_pair_a8,
  __ccc_pair_a9,
  __ccc_pair_aa,
  __ccc_pair_ab,
  __ccc_pair_ac,
  __ccc_pair_ad,
  __ccc_pair_ae,
  __ccc_pair_af,
  __ccc_pair_ag,
  __ccc_pair_ah,
  __ccc_pair_ai,
  __ccc_pair_aj,
  __ccc_pair_ak,
  __ccc_pair_al,
  __ccc_pair_am,
  __ccc_pair_an,
  __ccc_pair_ao,
  __ccc_pair_ap,
  __ccc_pair_aq,
  __ccc_pair_ar,
  __ccc_pair_as,
  __ccc_pair_at,
  __ccc_pair_au,
  __ccc_pair_av,
  __ccc_pair_aw,
  __ccc_pair_ax,
  __ccc_pair_ay,
  __ccc_pair_az,
  __ccc_pair_b0,
  __ccc_pair_b1,
  __ccc_pair_b2,
  __ccc_pair_b3,
  __ccc_pair_b4,
  __ccc_pair_b5,
  __ccc_pair_b6,
  __ccc_pair_b7,
  __ccc_pair_b8,
  __ccc_pair_b9,
  __ccc_pair_ba,
  __ccc_pair_bb,
  __ccc_pair_bc,
  __ccc_pair_bd,
  __ccc_pair_be,
  __ccc_pair_bf,
  __ccc_pair_bg,
  __ccc_pair_bh,
  __ccc_pair_bi,
  __ccc_pair_bj,
  __ccc_pair_bk,
  __ccc_pair_bl,
  __ccc_pair_bm,
  __ccc_pair_bn,
  __ccc_pair_bo,
  __ccc_pair_bp,
  __ccc_pair_bq,
  __ccc_pair_br,
  __ccc_pair_bs,
  __ccc_pair_bt,
  __ccc_pair_bu,
  __ccc_pair_bv,
  __ccc_pair_bw,
  __ccc_pair_bx,
  __ccc_pair_by,
  __ccc_pair_bz,
  __ccc_pair_c0,
  __ccc_pair_c1,
  __ccc_pair_c2,
  __ccc_pair_c3,
  __ccc_pair_c4,
  __ccc_pair_c5,
  __ccc_pair_c6,
  __ccc_pair_c7,
  __ccc_pair_c8,
  __ccc_pair_c9,
  __ccc_pair_ca,
  __ccc_pair_cb,
  __ccc_pair_cc,
  __ccc_pair_cd,
  __ccc_pair_ce,
  __ccc_pair_cf,
  __ccc_pair_cg,
  __ccc_pair_ch,
  __ccc_pair_ci,
  __ccc_pair_cj,
  __ccc_pair_ck,
  __ccc_pair_cl,
  __ccc_pair_cm,
  __ccc_pair_cn,
  __ccc_pair_co,
  __ccc_pair_cp,
  __ccc_pair_cq,
  __ccc_pair_cr,
  __ccc_pair_cs,
  __ccc_pair_ct,
  __ccc_pair_cu,
  __ccc_pair_cv,
  __ccc_pair_cw,
  __ccc_pair_cx,
  __ccc_pair_cy,
  __ccc_pair_cz,
  __ccc_pair_d0,
  __ccc_pair_d1,
  __ccc_pair_d2,
  __ccc_pair_d3,
  __ccc_pair_d4,
  __ccc_pair_d5,
  __ccc_pair_d6,
  __ccc_pair_d7,
  __ccc_pair_d8,
  __ccc_pair_d9,
  __ccc_pair_da,
  __ccc_pair_db,
  __ccc_pair_dc,
  __ccc_pair_dd,
  __ccc_pair_de,
  __ccc_pair_df,
  __ccc_pair_dg,
  __ccc_pair_dh,
  __ccc_pair_di,
  __ccc_pair_dj,
  __ccc_pair_dk,
  __ccc_pair_dl,
  __ccc_pair_dm,
  __ccc_pair_dn,
  __ccc_pair_do,
  __ccc_pair_dp,
  __ccc_pair_dq,
  __ccc_pair_dr,
  __ccc_pair_ds,
  __ccc_pair_dt,
  __ccc_pair_du,
  __ccc_pair_dv,
  __ccc_pair_dw,
  __ccc_pair_dx,
  __ccc_pair_dy,
  __ccc_pair_dz,
  __ccc_pair_e0,
  __ccc_pair_e1,
  __ccc_pair_e2,
  __ccc_pair_e3,
  __ccc_pair_e4,
  __ccc_pair_e5,
  __ccc_pair_e6,
  __ccc_pair_e7,
  __ccc_pair_e8,
  __ccc_pair_e9,
  __ccc_pair_ea,
  __ccc_pair_eb,
  __ccc_pair_ec,
  __ccc_pair_ed,
  __ccc_pair_ee,
  __ccc_pair_ef,
  __ccc_pair_eg,
  __ccc_pair_eh,
  __ccc_pair_ei,
  __ccc_pair_ej,
  __ccc_pair_ek,
  __ccc_pair_el,
  __ccc_pair_em,
  __ccc_pair_en,
  __ccc_pair_eo,
  __ccc_pair_ep,
  __ccc_pair_eq,
  __ccc_pair_er,
  __ccc_pair_es,
  __ccc_pair_et,
  __ccc_pair_eu,
  __ccc_pair_ev,
  __ccc_pair_ew,
])
private let __ccc_rangePair_0: _T2 = (0x0...<0x300, .init(rawValue: 0))
private let __ccc_rangePair_1: _T2 = (0x300....0x314, .init(rawValue: 230))
private let __ccc_rangePair_2: _T2 = (0x31c....0x320, .init(rawValue: 220))
private let __ccc_rangePair_3: _T2 = (0x329....0x333, .init(rawValue: 220))
private let __ccc_rangePair_4: _T2 = (0x334....0x338, .init(rawValue: 1))
private let __ccc_rangePair_5: _T2 = (0x33d....0x344, .init(rawValue: 230))
private let __ccc_rangePair_6: _T2 = (0x363....0x36f, .init(rawValue: 230))
private let __ccc_rangePair_7: _T2 = (0x370...<0x483, .init(rawValue: 0))
private let __ccc_rangePair_8: _T2 = (0x483....0x487, .init(rawValue: 230))
private let __ccc_rangePair_9: _T2 = (0x488...<0x591, .init(rawValue: 0))
private let __ccc_rangePair_a: _T2 = (0x59c....0x5a1, .init(rawValue: 230))
private let __ccc_rangePair_b: _T2 = (0x5a2....0x5a7, .init(rawValue: 220))
private let __ccc_rangePair_c: _T2 = (0x5c7<...<0x610, .init(rawValue: 0))
private let __ccc_rangePair_d: _T2 = (0x610....0x617, .init(rawValue: 230))
private let __ccc_rangePair_e: _T2 = (0x61b...<0x64b, .init(rawValue: 0))
private let __ccc_rangePair_f: _T2 = (0x657....0x65b, .init(rawValue: 230))
private let __ccc_rangePair_g: _T2 = (0x660...<0x670, .init(rawValue: 0))
private let __ccc_rangePair_h: _T2 = (0x671...<0x6d6, .init(rawValue: 0))
private let __ccc_rangePair_i: _T2 = (0x6d6....0x6dc, .init(rawValue: 230))
private let __ccc_rangePair_j: _T2 = (0x6ee...<0x711, .init(rawValue: 0))
private let __ccc_rangePair_k: _T2 = (0x712...<0x730, .init(rawValue: 0))
private let __ccc_rangePair_l: _T2 = (0x74a<...<0x7eb, .init(rawValue: 0))
private let __ccc_rangePair_m: _T2 = (0x7eb....0x7f1, .init(rawValue: 230))
private let __ccc_rangePair_n: _T2 = (0x7f4...<0x7fd, .init(rawValue: 0))
private let __ccc_rangePair_o: _T2 = (0x7fe...<0x816, .init(rawValue: 0))
private let __ccc_rangePair_p: _T2 = (0x81b....0x823, .init(rawValue: 230))
private let __ccc_rangePair_q: _T2 = (0x829....0x82d, .init(rawValue: 230))
private let __ccc_rangePair_r: _T2 = (0x82d<...<0x859, .init(rawValue: 0))
private let __ccc_rangePair_s: _T2 = (0x85b<...<0x8d3, .init(rawValue: 0))
private let __ccc_rangePair_t: _T2 = (0x8d4....0x8e1, .init(rawValue: 230))
private let __ccc_rangePair_u: _T2 = (0x8fb....0x8ff, .init(rawValue: 230))
private let __ccc_rangePair_v: _T2 = (0x900...<0x93c, .init(rawValue: 0))
private let __ccc_rangePair_w: _T2 = (0x93d...<0x94d, .init(rawValue: 0))
private let __ccc_rangePair_x: _T2 = (0x955...<0x9bc, .init(rawValue: 0))
private let __ccc_rangePair_y: _T2 = (0x9bd...<0x9cd, .init(rawValue: 0))
private let __ccc_rangePair_z: _T2 = (0x9ce...<0x9fe, .init(rawValue: 0))
private let __ccc_rangePair_10: _T2 = (0x9fe<...<0xa3c, .init(rawValue: 0))
private let __ccc_rangePair_11: _T2 = (0xa3c<...<0xa4d, .init(rawValue: 0))
private let __ccc_rangePair_12: _T2 = (0xa4d<...<0xabc, .init(rawValue: 0))
private let __ccc_rangePair_13: _T2 = (0xabd...<0xacd, .init(rawValue: 0))
private let __ccc_rangePair_14: _T2 = (0xacd<...<0xb3c, .init(rawValue: 0))
private let __ccc_rangePair_15: _T2 = (0xb3d...<0xb4d, .init(rawValue: 0))
private let __ccc_rangePair_16: _T2 = (0xb4d<...<0xbcd, .init(rawValue: 0))
private let __ccc_rangePair_17: _T2 = (0xbcd<...<0xc4d, .init(rawValue: 0))
private let __ccc_rangePair_18: _T2 = (0xc4d<...<0xc55, .init(rawValue: 0))
private let __ccc_rangePair_19: _T2 = (0xc56<...<0xcbc, .init(rawValue: 0))
private let __ccc_rangePair_1a: _T2 = (0xcbd...<0xccd, .init(rawValue: 0))
private let __ccc_rangePair_1b: _T2 = (0xccd<...<0xd3b, .init(rawValue: 0))
private let __ccc_rangePair_1c: _T2 = (0xd3d...<0xd4d, .init(rawValue: 0))
private let __ccc_rangePair_1d: _T2 = (0xd4e...<0xdca, .init(rawValue: 0))
private let __ccc_rangePair_1e: _T2 = (0xdca<...<0xe38, .init(rawValue: 0))
private let __ccc_rangePair_1f: _T2 = (0xe3a<...<0xe48, .init(rawValue: 0))
private let __ccc_rangePair_1g: _T2 = (0xe4c...<0xeb8, .init(rawValue: 0))
private let __ccc_rangePair_1h: _T2 = (0xebb...<0xec8, .init(rawValue: 0))
private let __ccc_rangePair_1i: _T2 = (0xecc...<0xf18, .init(rawValue: 0))
private let __ccc_rangePair_1j: _T2 = (0xf1a...<0xf35, .init(rawValue: 0))
private let __ccc_rangePair_1k: _T2 = (0xf3a...<0xf71, .init(rawValue: 0))
private let __ccc_rangePair_1l: _T2 = (0xf75...<0xf7a, .init(rawValue: 0))
private let __ccc_rangePair_1m: _T2 = (0xf88...<0xfc6, .init(rawValue: 0))
private let __ccc_rangePair_1n: _T2 = (0xfc7...<0x1037, .init(rawValue: 0))
private let __ccc_rangePair_1o: _T2 = (0x103b...<0x108d, .init(rawValue: 0))
private let __ccc_rangePair_1p: _T2 = (0x108e...<0x135d, .init(rawValue: 0))
private let __ccc_rangePair_1q: _T2 = (0x1360...<0x1714, .init(rawValue: 0))
private let __ccc_rangePair_1r: _T2 = (0x1714<...<0x1734, .init(rawValue: 0))
private let __ccc_rangePair_1s: _T2 = (0x1735...<0x17d2, .init(rawValue: 0))
private let __ccc_rangePair_1t: _T2 = (0x17d3...<0x17dd, .init(rawValue: 0))
private let __ccc_rangePair_1u: _T2 = (0x17dd<...<0x18a9, .init(rawValue: 0))
private let __ccc_rangePair_1v: _T2 = (0x18aa...<0x1939, .init(rawValue: 0))
private let __ccc_rangePair_1w: _T2 = (0x193b<...<0x1a17, .init(rawValue: 0))
private let __ccc_rangePair_1x: _T2 = (0x1a19...<0x1a60, .init(rawValue: 0))
private let __ccc_rangePair_1y: _T2 = (0x1a61...<0x1a75, .init(rawValue: 0))
private let __ccc_rangePair_1z: _T2 = (0x1a75....0x1a7c, .init(rawValue: 230))
private let __ccc_rangePair_20: _T2 = (0x1a80...<0x1ab0, .init(rawValue: 0))
private let __ccc_rangePair_21: _T2 = (0x1ab0....0x1ab4, .init(rawValue: 230))
private let __ccc_rangePair_22: _T2 = (0x1ab5....0x1aba, .init(rawValue: 220))
private let __ccc_rangePair_23: _T2 = (0x1abe...<0x1b34, .init(rawValue: 0))
private let __ccc_rangePair_24: _T2 = (0x1b35...<0x1b44, .init(rawValue: 0))
private let __ccc_rangePair_25: _T2 = (0x1b45...<0x1b6b, .init(rawValue: 0))
private let __ccc_rangePair_26: _T2 = (0x1b6d....0x1b73, .init(rawValue: 230))
private let __ccc_rangePair_27: _T2 = (0x1b74...<0x1baa, .init(rawValue: 0))
private let __ccc_rangePair_28: _T2 = (0x1bac...<0x1be6, .init(rawValue: 0))
private let __ccc_rangePair_29: _T2 = (0x1be7...<0x1bf2, .init(rawValue: 0))
private let __ccc_rangePair_2a: _T2 = (0x1bf3<...<0x1c37, .init(rawValue: 0))
private let __ccc_rangePair_2b: _T2 = (0x1c37<...<0x1cd0, .init(rawValue: 0))
private let __ccc_rangePair_2c: _T2 = (0x1cd5....0x1cd9, .init(rawValue: 220))
private let __ccc_rangePair_2d: _T2 = (0x1ce2....0x1ce8, .init(rawValue: 1))
private let __ccc_rangePair_2e: _T2 = (0x1cee...<0x1cf4, .init(rawValue: 0))
private let __ccc_rangePair_2f: _T2 = (0x1cfa...<0x1dc0, .init(rawValue: 0))
private let __ccc_rangePair_2g: _T2 = (0x1dc3....0x1dc9, .init(rawValue: 230))
private let __ccc_rangePair_2h: _T2 = (0x1dd1....0x1df5, .init(rawValue: 230))
private let __ccc_rangePair_2i: _T2 = (0x1e00...<0x20d0, .init(rawValue: 0))
private let __ccc_rangePair_2j: _T2 = (0x20f0<...<0x2cef, .init(rawValue: 0))
private let __ccc_rangePair_2k: _T2 = (0x2cf2...<0x2d7f, .init(rawValue: 0))
private let __ccc_rangePair_2l: _T2 = (0x2d80...<0x2de0, .init(rawValue: 0))
private let __ccc_rangePair_2m: _T2 = (0x2de0....0x2dff, .init(rawValue: 230))
private let __ccc_rangePair_2n: _T2 = (0x2e00...<0x302a, .init(rawValue: 0))
private let __ccc_rangePair_2o: _T2 = (0x3030...<0x3099, .init(rawValue: 0))
private let __ccc_rangePair_2p: _T2 = (0x309b...<0xa66f, .init(rawValue: 0))
private let __ccc_rangePair_2q: _T2 = (0xa674....0xa67d, .init(rawValue: 230))
private let __ccc_rangePair_2r: _T2 = (0xa67e...<0xa69e, .init(rawValue: 0))
private let __ccc_rangePair_2s: _T2 = (0xa6a0...<0xa6f0, .init(rawValue: 0))
private let __ccc_rangePair_2t: _T2 = (0xa6f2...<0xa806, .init(rawValue: 0))
private let __ccc_rangePair_2u: _T2 = (0xa807...<0xa8c4, .init(rawValue: 0))
private let __ccc_rangePair_2v: _T2 = (0xa8c5...<0xa8e0, .init(rawValue: 0))
private let __ccc_rangePair_2w: _T2 = (0xa8e0....0xa8f1, .init(rawValue: 230))
private let __ccc_rangePair_2x: _T2 = (0xa8f2...<0xa92b, .init(rawValue: 0))
private let __ccc_rangePair_2y: _T2 = (0xa92e...<0xa953, .init(rawValue: 0))
private let __ccc_rangePair_2z: _T2 = (0xa953<...<0xa9b3, .init(rawValue: 0))
private let __ccc_rangePair_30: _T2 = (0xa9b4...<0xa9c0, .init(rawValue: 0))
private let __ccc_rangePair_31: _T2 = (0xa9c1...<0xaab0, .init(rawValue: 0))
private let __ccc_rangePair_32: _T2 = (0xaab9...<0xaabe, .init(rawValue: 0))
private let __ccc_rangePair_33: _T2 = (0xaac2...<0xaaf6, .init(rawValue: 0))
private let __ccc_rangePair_34: _T2 = (0xaaf6<...<0xabed, .init(rawValue: 0))
private let __ccc_rangePair_35: _T2 = (0xabed<...<0xfb1e, .init(rawValue: 0))
private let __ccc_rangePair_36: _T2 = (0xfb1f...<0xfe20, .init(rawValue: 0))
private let __ccc_rangePair_37: _T2 = (0xfe20....0xfe26, .init(rawValue: 230))
private let __ccc_rangePair_38: _T2 = (0xfe27....0xfe2d, .init(rawValue: 220))
private let __ccc_rangePair_39: _T2 = (0xfe30...<0x101fd, .init(rawValue: 0))
private let __ccc_rangePair_3a: _T2 = (0x101fd<...<0x102e0, .init(rawValue: 0))
private let __ccc_rangePair_3b: _T2 = (0x102e1...<0x10376, .init(rawValue: 0))
private let __ccc_rangePair_3c: _T2 = (0x10376....0x1037a, .init(rawValue: 230))
private let __ccc_rangePair_3d: _T2 = (0x1037a<...<0x10a0d, .init(rawValue: 0))
private let __ccc_rangePair_3e: _T2 = (0x10a10...<0x10a38, .init(rawValue: 0))
private let __ccc_rangePair_3f: _T2 = (0x10a40...<0x10ae5, .init(rawValue: 0))
private let __ccc_rangePair_3g: _T2 = (0x10ae6<...<0x10d24, .init(rawValue: 0))
private let __ccc_rangePair_3h: _T2 = (0x10d27<...<0x10f46, .init(rawValue: 0))
private let __ccc_rangePair_3i: _T2 = (0x10f51...<0x11046, .init(rawValue: 0))
private let __ccc_rangePair_3j: _T2 = (0x11047...<0x1107f, .init(rawValue: 0))
private let __ccc_rangePair_3k: _T2 = (0x11080...<0x110b9, .init(rawValue: 0))
private let __ccc_rangePair_3l: _T2 = (0x110bb...<0x11100, .init(rawValue: 0))
private let __ccc_rangePair_3m: _T2 = (0x11103...<0x11133, .init(rawValue: 0))
private let __ccc_rangePair_3n: _T2 = (0x11134<...<0x11173, .init(rawValue: 0))
private let __ccc_rangePair_3o: _T2 = (0x11174...<0x111c0, .init(rawValue: 0))
private let __ccc_rangePair_3p: _T2 = (0x111c1...<0x111ca, .init(rawValue: 0))
private let __ccc_rangePair_3q: _T2 = (0x111cb...<0x11235, .init(rawValue: 0))
private let __ccc_rangePair_3r: _T2 = (0x11237...<0x112e9, .init(rawValue: 0))
private let __ccc_rangePair_3s: _T2 = (0x112ea<...<0x1133b, .init(rawValue: 0))
private let __ccc_rangePair_3t: _T2 = (0x1133d...<0x1134d, .init(rawValue: 0))
private let __ccc_rangePair_3u: _T2 = (0x1134d<...<0x11366, .init(rawValue: 0))
private let __ccc_rangePair_3v: _T2 = (0x11366....0x1136c, .init(rawValue: 230))
private let __ccc_rangePair_3w: _T2 = (0x11370....0x11374, .init(rawValue: 230))
private let __ccc_rangePair_3x: _T2 = (0x11374<...<0x11442, .init(rawValue: 0))
private let __ccc_rangePair_3y: _T2 = (0x11447...<0x1145e, .init(rawValue: 0))
private let __ccc_rangePair_3z: _T2 = (0x1145f...<0x114c2, .init(rawValue: 0))
private let __ccc_rangePair_40: _T2 = (0x114c4...<0x115bf, .init(rawValue: 0))
private let __ccc_rangePair_41: _T2 = (0x115c1...<0x1163f, .init(rawValue: 0))
private let __ccc_rangePair_42: _T2 = (0x11640...<0x116b6, .init(rawValue: 0))
private let __ccc_rangePair_43: _T2 = (0x116b8...<0x1172b, .init(rawValue: 0))
private let __ccc_rangePair_44: _T2 = (0x1172b<...<0x11839, .init(rawValue: 0))
private let __ccc_rangePair_45: _T2 = (0x1183b...<0x119e0, .init(rawValue: 0))
private let __ccc_rangePair_46: _T2 = (0x119e1...<0x11a34, .init(rawValue: 0))
private let __ccc_rangePair_47: _T2 = (0x11a35...<0x11a47, .init(rawValue: 0))
private let __ccc_rangePair_48: _T2 = (0x11a47<...<0x11a99, .init(rawValue: 0))
private let __ccc_rangePair_49: _T2 = (0x11a9a...<0x11c3f, .init(rawValue: 0))
private let __ccc_rangePair_4a: _T2 = (0x11c40...<0x11d42, .init(rawValue: 0))
private let __ccc_rangePair_4b: _T2 = (0x11d46...<0x11d97, .init(rawValue: 0))
private let __ccc_rangePair_4c: _T2 = (0x11d98...<0x16af0, .init(rawValue: 0))
private let __ccc_rangePair_4d: _T2 = (0x16af0....0x16af4, .init(rawValue: 1))
private let __ccc_rangePair_4e: _T2 = (0x16af5...<0x16b30, .init(rawValue: 0))
private let __ccc_rangePair_4f: _T2 = (0x16b30....0x16b36, .init(rawValue: 230))
private let __ccc_rangePair_4g: _T2 = (0x16b37...<0x1bc9e, .init(rawValue: 0))
private let __ccc_rangePair_4h: _T2 = (0x1bc9f...<0x1d165, .init(rawValue: 0))
private let __ccc_rangePair_4i: _T2 = (0x1d16e....0x1d172, .init(rawValue: 216))
private let __ccc_rangePair_4j: _T2 = (0x1d173...<0x1d17b, .init(rawValue: 0))
private let __ccc_rangePair_4k: _T2 = (0x1d17b....0x1d182, .init(rawValue: 220))
private let __ccc_rangePair_4l: _T2 = (0x1d185....0x1d189, .init(rawValue: 230))
private let __ccc_rangePair_4m: _T2 = (0x1d18c...<0x1d1aa, .init(rawValue: 0))
private let __ccc_rangePair_4n: _T2 = (0x1d1ae...<0x1d242, .init(rawValue: 0))
private let __ccc_rangePair_4o: _T2 = (0x1d245...<0x1e000, .init(rawValue: 0))
private let __ccc_rangePair_4p: _T2 = (0x1e000....0x1e006, .init(rawValue: 230))
private let __ccc_rangePair_4q: _T2 = (0x1e008....0x1e018, .init(rawValue: 230))
private let __ccc_rangePair_4r: _T2 = (0x1e01b....0x1e021, .init(rawValue: 230))
private let __ccc_rangePair_4s: _T2 = (0x1e026....0x1e02a, .init(rawValue: 230))
private let __ccc_rangePair_4t: _T2 = (0x1e02a<...<0x1e130, .init(rawValue: 0))
private let __ccc_rangePair_4u: _T2 = (0x1e130....0x1e136, .init(rawValue: 230))
private let __ccc_rangePair_4v: _T2 = (0x1e137...<0x1e2ec, .init(rawValue: 0))
private let __ccc_rangePair_4w: _T2 = (0x1e2f0...<0x1e8d0, .init(rawValue: 0))
private let __ccc_rangePair_4x: _T2 = (0x1e8d0....0x1e8d6, .init(rawValue: 220))
private let __ccc_rangePair_4y: _T2 = (0x1e8d6<...<0x1e944, .init(rawValue: 0))
private let __ccc_rangePair_4z: _T2 = (0x1e944....0x1e949, .init(rawValue: 230))
private let __ccc_rangePair_50: _T2 = (0x1e94b....0x10ffff, .init(rawValue: 0))
private let __ccc_rangePairArray: _T3 = [
  __ccc_rangePair_0,
  __ccc_rangePair_1,
  __ccc_rangePair_2,
  __ccc_rangePair_3,
  __ccc_rangePair_4,
  __ccc_rangePair_5,
  __ccc_rangePair_6,
  __ccc_rangePair_7,
  __ccc_rangePair_8,
  __ccc_rangePair_9,
  __ccc_rangePair_a,
  __ccc_rangePair_b,
  __ccc_rangePair_c,
  __ccc_rangePair_d,
  __ccc_rangePair_e,
  __ccc_rangePair_f,
  __ccc_rangePair_g,
  __ccc_rangePair_h,
  __ccc_rangePair_i,
  __ccc_rangePair_j,
  __ccc_rangePair_k,
  __ccc_rangePair_l,
  __ccc_rangePair_m,
  __ccc_rangePair_n,
  __ccc_rangePair_o,
  __ccc_rangePair_p,
  __ccc_rangePair_q,
  __ccc_rangePair_r,
  __ccc_rangePair_s,
  __ccc_rangePair_t,
  __ccc_rangePair_u,
  __ccc_rangePair_v,
  __ccc_rangePair_w,
  __ccc_rangePair_x,
  __ccc_rangePair_y,
  __ccc_rangePair_z,
  __ccc_rangePair_10,
  __ccc_rangePair_11,
  __ccc_rangePair_12,
  __ccc_rangePair_13,
  __ccc_rangePair_14,
  __ccc_rangePair_15,
  __ccc_rangePair_16,
  __ccc_rangePair_17,
  __ccc_rangePair_18,
  __ccc_rangePair_19,
  __ccc_rangePair_1a,
  __ccc_rangePair_1b,
  __ccc_rangePair_1c,
  __ccc_rangePair_1d,
  __ccc_rangePair_1e,
  __ccc_rangePair_1f,
  __ccc_rangePair_1g,
  __ccc_rangePair_1h,
  __ccc_rangePair_1i,
  __ccc_rangePair_1j,
  __ccc_rangePair_1k,
  __ccc_rangePair_1l,
  __ccc_rangePair_1m,
  __ccc_rangePair_1n,
  __ccc_rangePair_1o,
  __ccc_rangePair_1p,
  __ccc_rangePair_1q,
  __ccc_rangePair_1r,
  __ccc_rangePair_1s,
  __ccc_rangePair_1t,
  __ccc_rangePair_1u,
  __ccc_rangePair_1v,
  __ccc_rangePair_1w,
  __ccc_rangePair_1x,
  __ccc_rangePair_1y,
  __ccc_rangePair_1z,
  __ccc_rangePair_20,
  __ccc_rangePair_21,
  __ccc_rangePair_22,
  __ccc_rangePair_23,
  __ccc_rangePair_24,
  __ccc_rangePair_25,
  __ccc_rangePair_26,
  __ccc_rangePair_27,
  __ccc_rangePair_28,
  __ccc_rangePair_29,
  __ccc_rangePair_2a,
  __ccc_rangePair_2b,
  __ccc_rangePair_2c,
  __ccc_rangePair_2d,
  __ccc_rangePair_2e,
  __ccc_rangePair_2f,
  __ccc_rangePair_2g,
  __ccc_rangePair_2h,
  __ccc_rangePair_2i,
  __ccc_rangePair_2j,
  __ccc_rangePair_2k,
  __ccc_rangePair_2l,
  __ccc_rangePair_2m,
  __ccc_rangePair_2n,
  __ccc_rangePair_2o,
  __ccc_rangePair_2p,
  __ccc_rangePair_2q,
  __ccc_rangePair_2r,
  __ccc_rangePair_2s,
  __ccc_rangePair_2t,
  __ccc_rangePair_2u,
  __ccc_rangePair_2v,
  __ccc_rangePair_2w,
  __ccc_rangePair_2x,
  __ccc_rangePair_2y,
  __ccc_rangePair_2z,
  __ccc_rangePair_30,
  __ccc_rangePair_31,
  __ccc_rangePair_32,
  __ccc_rangePair_33,
  __ccc_rangePair_34,
  __ccc_rangePair_35,
  __ccc_rangePair_36,
  __ccc_rangePair_37,
  __ccc_rangePair_38,
  __ccc_rangePair_39,
  __ccc_rangePair_3a,
  __ccc_rangePair_3b,
  __ccc_rangePair_3c,
  __ccc_rangePair_3d,
  __ccc_rangePair_3e,
  __ccc_rangePair_3f,
  __ccc_rangePair_3g,
  __ccc_rangePair_3h,
  __ccc_rangePair_3i,
  __ccc_rangePair_3j,
  __ccc_rangePair_3k,
  __ccc_rangePair_3l,
  __ccc_rangePair_3m,
  __ccc_rangePair_3n,
  __ccc_rangePair_3o,
  __ccc_rangePair_3p,
  __ccc_rangePair_3q,
  __ccc_rangePair_3r,
  __ccc_rangePair_3s,
  __ccc_rangePair_3t,
  __ccc_rangePair_3u,
  __ccc_rangePair_3v,
  __ccc_rangePair_3w,
  __ccc_rangePair_3x,
  __ccc_rangePair_3y,
  __ccc_rangePair_3z,
  __ccc_rangePair_40,
  __ccc_rangePair_41,
  __ccc_rangePair_42,
  __ccc_rangePair_43,
  __ccc_rangePair_44,
  __ccc_rangePair_45,
  __ccc_rangePair_46,
  __ccc_rangePair_47,
  __ccc_rangePair_48,
  __ccc_rangePair_49,
  __ccc_rangePair_4a,
  __ccc_rangePair_4b,
  __ccc_rangePair_4c,
  __ccc_rangePair_4d,
  __ccc_rangePair_4e,
  __ccc_rangePair_4f,
  __ccc_rangePair_4g,
  __ccc_rangePair_4h,
  __ccc_rangePair_4i,
  __ccc_rangePair_4j,
  __ccc_rangePair_4k,
  __ccc_rangePair_4l,
  __ccc_rangePair_4m,
  __ccc_rangePair_4n,
  __ccc_rangePair_4o,
  __ccc_rangePair_4p,
  __ccc_rangePair_4q,
  __ccc_rangePair_4r,
  __ccc_rangePair_4s,
  __ccc_rangePair_4t,
  __ccc_rangePair_4u,
  __ccc_rangePair_4v,
  __ccc_rangePair_4w,
  __ccc_rangePair_4x,
  __ccc_rangePair_4y,
  __ccc_rangePair_4z,
  __ccc_rangePair_50,
]
private let __ccc_rangeDictionary = RangeDictionary<Unicode.Scalar.Value, _T0>(carefullySortedRangesAndValues: __ccc_rangePairArray)
internal let _ccc = UnicodeScalarValueDictionary<Unicode.CanonicalCombiningClass>(dictionary: __ccc_dictionary, rangeDictionary: __ccc_rangeDictionary)
