//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://www.unicode.org/Public/UCD/latest/ucd/extracted/DerivedJoiningType.txt
// Last-Modified: 2019-03-11T17:21:53Z
// ETag: "774063-8a7c-583d4cf03ee40"

/*
  UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE
  
  See <a href="https://www.unicode.org/copyright.html">Terms of Use</a> for definitions of Unicode Inc.'s
  Data Files and Software.
  NOTICE TO USER: Carefully read the following legal agreement.
  BY DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S
  DATA FILES ("DATA FILES"), AND/OR SOFTWARE ("SOFTWARE"),
  YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
  TERMS AND CONDITIONS OF THIS AGREEMENT.
  IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE
  THE DATA FILES OR SOFTWARE.
  COPYRIGHT AND PERMISSION NOTICE
  Copyright © 1991-2020 Unicode, Inc. All rights reserved.
  Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
  Permission is hereby granted, free of charge, to any person obtaining
  a copy of the Unicode data files and any associated documentation
  (the "Data Files") or Unicode software and any associated documentation
  (the "Software") to deal in the Data Files or Software
  without restriction, including without limitation the rights to use,
  copy, modify, merge, publish, distribute, and/or sell copies of
  the Data Files or Software, and to permit persons to whom the Data Files
  or Software are furnished to do so, provided that either
  (a) this copyright and permission notice appear with all copies
  of the Data Files or Software, or
  (b) this copyright and permission notice appear in associated
  Documentation.
  THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
  ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT OF THIRD PARTY RIGHTS.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
  NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
  DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
  DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
  TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
  PERFORMANCE OF THE DATA FILES OR SOFTWARE.
  Except as contained in this notice, the name of a copyright holder
  shall not be used in advertising or otherwise to promote the sale,
  use or other dealings in these Data Files or Software without prior
  written authorization of the copyright holder.
*/

// Required Modules
import Ranges

// Type Aliases
private typealias _T0 = Unicode.JoiningType
private typealias _T1 = (Unicode.Scalar.Value, _T0)
private typealias _T2 = (AnyRange<UInt32>, _T0)
private typealias _T3 = Array<_T2>

private let __jt_pair_0: _T1 = (0xad, .transparent)
private let __jt_pair_1: _T1 = (0x5bf, .transparent)
private let __jt_pair_2: _T1 = (0x5c7, .transparent)
private let __jt_pair_3: _T1 = (0x61c, .transparent)
private let __jt_pair_4: _T1 = (0x620, .dualJoining)
private let __jt_pair_5: _T1 = (0x626, .dualJoining)
private let __jt_pair_6: _T1 = (0x627, .rightJoining)
private let __jt_pair_7: _T1 = (0x628, .dualJoining)
private let __jt_pair_8: _T1 = (0x629, .rightJoining)
private let __jt_pair_9: _T1 = (0x640, .joinCausing)
private let __jt_pair_a: _T1 = (0x648, .rightJoining)
private let __jt_pair_b: _T1 = (0x670, .transparent)
private let __jt_pair_c: _T1 = (0x6c0, .rightJoining)
private let __jt_pair_d: _T1 = (0x6cc, .dualJoining)
private let __jt_pair_e: _T1 = (0x6cd, .rightJoining)
private let __jt_pair_f: _T1 = (0x6ce, .dualJoining)
private let __jt_pair_g: _T1 = (0x6cf, .rightJoining)
private let __jt_pair_h: _T1 = (0x6d5, .rightJoining)
private let __jt_pair_i: _T1 = (0x6ff, .dualJoining)
private let __jt_pair_j: _T1 = (0x70f, .transparent)
private let __jt_pair_k: _T1 = (0x710, .rightJoining)
private let __jt_pair_l: _T1 = (0x711, .transparent)
private let __jt_pair_m: _T1 = (0x71e, .rightJoining)
private let __jt_pair_n: _T1 = (0x728, .rightJoining)
private let __jt_pair_o: _T1 = (0x729, .dualJoining)
private let __jt_pair_p: _T1 = (0x72a, .rightJoining)
private let __jt_pair_q: _T1 = (0x72b, .dualJoining)
private let __jt_pair_r: _T1 = (0x72c, .rightJoining)
private let __jt_pair_s: _T1 = (0x72f, .rightJoining)
private let __jt_pair_t: _T1 = (0x74d, .rightJoining)
private let __jt_pair_u: _T1 = (0x771, .rightJoining)
private let __jt_pair_v: _T1 = (0x772, .dualJoining)
private let __jt_pair_w: _T1 = (0x7fa, .joinCausing)
private let __jt_pair_x: _T1 = (0x7fd, .transparent)
private let __jt_pair_y: _T1 = (0x840, .rightJoining)
private let __jt_pair_z: _T1 = (0x848, .dualJoining)
private let __jt_pair_10: _T1 = (0x849, .rightJoining)
private let __jt_pair_11: _T1 = (0x854, .rightJoining)
private let __jt_pair_12: _T1 = (0x855, .dualJoining)
private let __jt_pair_13: _T1 = (0x860, .dualJoining)
private let __jt_pair_14: _T1 = (0x867, .rightJoining)
private let __jt_pair_15: _T1 = (0x868, .dualJoining)
private let __jt_pair_16: _T1 = (0x8ae, .rightJoining)
private let __jt_pair_17: _T1 = (0x8b9, .rightJoining)
private let __jt_pair_18: _T1 = (0x93a, .transparent)
private let __jt_pair_19: _T1 = (0x93c, .transparent)
private let __jt_pair_1a: _T1 = (0x94d, .transparent)
private let __jt_pair_1b: _T1 = (0x981, .transparent)
private let __jt_pair_1c: _T1 = (0x9bc, .transparent)
private let __jt_pair_1d: _T1 = (0x9cd, .transparent)
private let __jt_pair_1e: _T1 = (0x9fe, .transparent)
private let __jt_pair_1f: _T1 = (0xa3c, .transparent)
private let __jt_pair_1g: _T1 = (0xa51, .transparent)
private let __jt_pair_1h: _T1 = (0xa75, .transparent)
private let __jt_pair_1i: _T1 = (0xabc, .transparent)
private let __jt_pair_1j: _T1 = (0xacd, .transparent)
private let __jt_pair_1k: _T1 = (0xb01, .transparent)
private let __jt_pair_1l: _T1 = (0xb3c, .transparent)
private let __jt_pair_1m: _T1 = (0xb3f, .transparent)
private let __jt_pair_1n: _T1 = (0xb4d, .transparent)
private let __jt_pair_1o: _T1 = (0xb56, .transparent)
private let __jt_pair_1p: _T1 = (0xb82, .transparent)
private let __jt_pair_1q: _T1 = (0xbc0, .transparent)
private let __jt_pair_1r: _T1 = (0xbcd, .transparent)
private let __jt_pair_1s: _T1 = (0xc00, .transparent)
private let __jt_pair_1t: _T1 = (0xc04, .transparent)
private let __jt_pair_1u: _T1 = (0xc81, .transparent)
private let __jt_pair_1v: _T1 = (0xcbc, .transparent)
private let __jt_pair_1w: _T1 = (0xcbf, .transparent)
private let __jt_pair_1x: _T1 = (0xcc6, .transparent)
private let __jt_pair_1y: _T1 = (0xd4d, .transparent)
private let __jt_pair_1z: _T1 = (0xdca, .transparent)
private let __jt_pair_20: _T1 = (0xdd6, .transparent)
private let __jt_pair_21: _T1 = (0xe31, .transparent)
private let __jt_pair_22: _T1 = (0xeb1, .transparent)
private let __jt_pair_23: _T1 = (0xf35, .transparent)
private let __jt_pair_24: _T1 = (0xf37, .transparent)
private let __jt_pair_25: _T1 = (0xf39, .transparent)
private let __jt_pair_26: _T1 = (0xfc6, .transparent)
private let __jt_pair_27: _T1 = (0x1082, .transparent)
private let __jt_pair_28: _T1 = (0x108d, .transparent)
private let __jt_pair_29: _T1 = (0x109d, .transparent)
private let __jt_pair_2a: _T1 = (0x17c6, .transparent)
private let __jt_pair_2b: _T1 = (0x17dd, .transparent)
private let __jt_pair_2c: _T1 = (0x1807, .dualJoining)
private let __jt_pair_2d: _T1 = (0x180a, .joinCausing)
private let __jt_pair_2e: _T1 = (0x18a9, .transparent)
private let __jt_pair_2f: _T1 = (0x18aa, .dualJoining)
private let __jt_pair_2g: _T1 = (0x1932, .transparent)
private let __jt_pair_2h: _T1 = (0x1a1b, .transparent)
private let __jt_pair_2i: _T1 = (0x1a56, .transparent)
private let __jt_pair_2j: _T1 = (0x1a60, .transparent)
private let __jt_pair_2k: _T1 = (0x1a62, .transparent)
private let __jt_pair_2l: _T1 = (0x1a7f, .transparent)
private let __jt_pair_2m: _T1 = (0x1b34, .transparent)
private let __jt_pair_2n: _T1 = (0x1b3c, .transparent)
private let __jt_pair_2o: _T1 = (0x1b42, .transparent)
private let __jt_pair_2p: _T1 = (0x1be6, .transparent)
private let __jt_pair_2q: _T1 = (0x1bed, .transparent)
private let __jt_pair_2r: _T1 = (0x1ced, .transparent)
private let __jt_pair_2s: _T1 = (0x1cf4, .transparent)
private let __jt_pair_2t: _T1 = (0x200b, .transparent)
private let __jt_pair_2u: _T1 = (0x200d, .joinCausing)
private let __jt_pair_2v: _T1 = (0x2d7f, .transparent)
private let __jt_pair_2w: _T1 = (0xa802, .transparent)
private let __jt_pair_2x: _T1 = (0xa806, .transparent)
private let __jt_pair_2y: _T1 = (0xa80b, .transparent)
private let __jt_pair_2z: _T1 = (0xa872, .leftJoining)
private let __jt_pair_30: _T1 = (0xa8ff, .transparent)
private let __jt_pair_31: _T1 = (0xa9b3, .transparent)
private let __jt_pair_32: _T1 = (0xa9e5, .transparent)
private let __jt_pair_33: _T1 = (0xaa43, .transparent)
private let __jt_pair_34: _T1 = (0xaa4c, .transparent)
private let __jt_pair_35: _T1 = (0xaa7c, .transparent)
private let __jt_pair_36: _T1 = (0xaab0, .transparent)
private let __jt_pair_37: _T1 = (0xaac1, .transparent)
private let __jt_pair_38: _T1 = (0xaaf6, .transparent)
private let __jt_pair_39: _T1 = (0xabe5, .transparent)
private let __jt_pair_3a: _T1 = (0xabe8, .transparent)
private let __jt_pair_3b: _T1 = (0xabed, .transparent)
private let __jt_pair_3c: _T1 = (0xfb1e, .transparent)
private let __jt_pair_3d: _T1 = (0xfeff, .transparent)
private let __jt_pair_3e: _T1 = (0x101fd, .transparent)
private let __jt_pair_3f: _T1 = (0x102e0, .transparent)
private let __jt_pair_3g: _T1 = (0x10a3f, .transparent)
private let __jt_pair_3h: _T1 = (0x10ac5, .rightJoining)
private let __jt_pair_3i: _T1 = (0x10ac7, .rightJoining)
private let __jt_pair_3j: _T1 = (0x10acd, .leftJoining)
private let __jt_pair_3k: _T1 = (0x10ad7, .leftJoining)
private let __jt_pair_3l: _T1 = (0x10add, .rightJoining)
private let __jt_pair_3m: _T1 = (0x10ae1, .rightJoining)
private let __jt_pair_3n: _T1 = (0x10ae4, .rightJoining)
private let __jt_pair_3o: _T1 = (0x10aef, .rightJoining)
private let __jt_pair_3p: _T1 = (0x10b80, .dualJoining)
private let __jt_pair_3q: _T1 = (0x10b81, .rightJoining)
private let __jt_pair_3r: _T1 = (0x10b82, .dualJoining)
private let __jt_pair_3s: _T1 = (0x10b89, .rightJoining)
private let __jt_pair_3t: _T1 = (0x10b8c, .rightJoining)
private let __jt_pair_3u: _T1 = (0x10b8d, .dualJoining)
private let __jt_pair_3v: _T1 = (0x10b90, .dualJoining)
private let __jt_pair_3w: _T1 = (0x10b91, .rightJoining)
private let __jt_pair_3x: _T1 = (0x10d00, .leftJoining)
private let __jt_pair_3y: _T1 = (0x10d22, .rightJoining)
private let __jt_pair_3z: _T1 = (0x10d23, .dualJoining)
private let __jt_pair_40: _T1 = (0x10f33, .rightJoining)
private let __jt_pair_41: _T1 = (0x10f54, .rightJoining)
private let __jt_pair_42: _T1 = (0x11001, .transparent)
private let __jt_pair_43: _T1 = (0x11173, .transparent)
private let __jt_pair_44: _T1 = (0x11234, .transparent)
private let __jt_pair_45: _T1 = (0x1123e, .transparent)
private let __jt_pair_46: _T1 = (0x112df, .transparent)
private let __jt_pair_47: _T1 = (0x11340, .transparent)
private let __jt_pair_48: _T1 = (0x11446, .transparent)
private let __jt_pair_49: _T1 = (0x1145e, .transparent)
private let __jt_pair_4a: _T1 = (0x114ba, .transparent)
private let __jt_pair_4b: _T1 = (0x1163d, .transparent)
private let __jt_pair_4c: _T1 = (0x116ab, .transparent)
private let __jt_pair_4d: _T1 = (0x116ad, .transparent)
private let __jt_pair_4e: _T1 = (0x116b7, .transparent)
private let __jt_pair_4f: _T1 = (0x119e0, .transparent)
private let __jt_pair_4g: _T1 = (0x11a47, .transparent)
private let __jt_pair_4h: _T1 = (0x11c3f, .transparent)
private let __jt_pair_4i: _T1 = (0x11d3a, .transparent)
private let __jt_pair_4j: _T1 = (0x11d47, .transparent)
private let __jt_pair_4k: _T1 = (0x11d95, .transparent)
private let __jt_pair_4l: _T1 = (0x11d97, .transparent)
private let __jt_pair_4m: _T1 = (0x16f4f, .transparent)
private let __jt_pair_4n: _T1 = (0x1da75, .transparent)
private let __jt_pair_4o: _T1 = (0x1da84, .transparent)
private let __jt_pair_4p: _T1 = (0xe0001, .transparent)
private let __jt_dictionary = Dictionary<Unicode.Scalar.Value, _T0>(uniqueKeysWithValues: [
  __jt_pair_0,
  __jt_pair_1,
  __jt_pair_2,
  __jt_pair_3,
  __jt_pair_4,
  __jt_pair_5,
  __jt_pair_6,
  __jt_pair_7,
  __jt_pair_8,
  __jt_pair_9,
  __jt_pair_a,
  __jt_pair_b,
  __jt_pair_c,
  __jt_pair_d,
  __jt_pair_e,
  __jt_pair_f,
  __jt_pair_g,
  __jt_pair_h,
  __jt_pair_i,
  __jt_pair_j,
  __jt_pair_k,
  __jt_pair_l,
  __jt_pair_m,
  __jt_pair_n,
  __jt_pair_o,
  __jt_pair_p,
  __jt_pair_q,
  __jt_pair_r,
  __jt_pair_s,
  __jt_pair_t,
  __jt_pair_u,
  __jt_pair_v,
  __jt_pair_w,
  __jt_pair_x,
  __jt_pair_y,
  __jt_pair_z,
  __jt_pair_10,
  __jt_pair_11,
  __jt_pair_12,
  __jt_pair_13,
  __jt_pair_14,
  __jt_pair_15,
  __jt_pair_16,
  __jt_pair_17,
  __jt_pair_18,
  __jt_pair_19,
  __jt_pair_1a,
  __jt_pair_1b,
  __jt_pair_1c,
  __jt_pair_1d,
  __jt_pair_1e,
  __jt_pair_1f,
  __jt_pair_1g,
  __jt_pair_1h,
  __jt_pair_1i,
  __jt_pair_1j,
  __jt_pair_1k,
  __jt_pair_1l,
  __jt_pair_1m,
  __jt_pair_1n,
  __jt_pair_1o,
  __jt_pair_1p,
  __jt_pair_1q,
  __jt_pair_1r,
  __jt_pair_1s,
  __jt_pair_1t,
  __jt_pair_1u,
  __jt_pair_1v,
  __jt_pair_1w,
  __jt_pair_1x,
  __jt_pair_1y,
  __jt_pair_1z,
  __jt_pair_20,
  __jt_pair_21,
  __jt_pair_22,
  __jt_pair_23,
  __jt_pair_24,
  __jt_pair_25,
  __jt_pair_26,
  __jt_pair_27,
  __jt_pair_28,
  __jt_pair_29,
  __jt_pair_2a,
  __jt_pair_2b,
  __jt_pair_2c,
  __jt_pair_2d,
  __jt_pair_2e,
  __jt_pair_2f,
  __jt_pair_2g,
  __jt_pair_2h,
  __jt_pair_2i,
  __jt_pair_2j,
  __jt_pair_2k,
  __jt_pair_2l,
  __jt_pair_2m,
  __jt_pair_2n,
  __jt_pair_2o,
  __jt_pair_2p,
  __jt_pair_2q,
  __jt_pair_2r,
  __jt_pair_2s,
  __jt_pair_2t,
  __jt_pair_2u,
  __jt_pair_2v,
  __jt_pair_2w,
  __jt_pair_2x,
  __jt_pair_2y,
  __jt_pair_2z,
  __jt_pair_30,
  __jt_pair_31,
  __jt_pair_32,
  __jt_pair_33,
  __jt_pair_34,
  __jt_pair_35,
  __jt_pair_36,
  __jt_pair_37,
  __jt_pair_38,
  __jt_pair_39,
  __jt_pair_3a,
  __jt_pair_3b,
  __jt_pair_3c,
  __jt_pair_3d,
  __jt_pair_3e,
  __jt_pair_3f,
  __jt_pair_3g,
  __jt_pair_3h,
  __jt_pair_3i,
  __jt_pair_3j,
  __jt_pair_3k,
  __jt_pair_3l,
  __jt_pair_3m,
  __jt_pair_3n,
  __jt_pair_3o,
  __jt_pair_3p,
  __jt_pair_3q,
  __jt_pair_3r,
  __jt_pair_3s,
  __jt_pair_3t,
  __jt_pair_3u,
  __jt_pair_3v,
  __jt_pair_3w,
  __jt_pair_3x,
  __jt_pair_3y,
  __jt_pair_3z,
  __jt_pair_40,
  __jt_pair_41,
  __jt_pair_42,
  __jt_pair_43,
  __jt_pair_44,
  __jt_pair_45,
  __jt_pair_46,
  __jt_pair_47,
  __jt_pair_48,
  __jt_pair_49,
  __jt_pair_4a,
  __jt_pair_4b,
  __jt_pair_4c,
  __jt_pair_4d,
  __jt_pair_4e,
  __jt_pair_4f,
  __jt_pair_4g,
  __jt_pair_4h,
  __jt_pair_4i,
  __jt_pair_4j,
  __jt_pair_4k,
  __jt_pair_4l,
  __jt_pair_4m,
  __jt_pair_4n,
  __jt_pair_4o,
  __jt_pair_4p,
])
private let __jt_rangePair_0: _T2 = (0x300....0x36f, .transparent)
private let __jt_rangePair_1: _T2 = (0x483....0x489, .transparent)
private let __jt_rangePair_2: _T2 = (0x591....0x5bd, .transparent)
private let __jt_rangePair_3: _T2 = (0x5c1....0x5c2, .transparent)
private let __jt_rangePair_4: _T2 = (0x5c4....0x5c5, .transparent)
private let __jt_rangePair_5: _T2 = (0x610....0x61a, .transparent)
private let __jt_rangePair_6: _T2 = (0x622....0x625, .rightJoining)
private let __jt_rangePair_7: _T2 = (0x62a....0x62e, .dualJoining)
private let __jt_rangePair_8: _T2 = (0x62f....0x632, .rightJoining)
private let __jt_rangePair_9: _T2 = (0x633....0x63f, .dualJoining)
private let __jt_rangePair_a: _T2 = (0x641....0x647, .dualJoining)
private let __jt_rangePair_b: _T2 = (0x649....0x64a, .dualJoining)
private let __jt_rangePair_c: _T2 = (0x64b....0x65f, .transparent)
private let __jt_rangePair_d: _T2 = (0x66e....0x66f, .dualJoining)
private let __jt_rangePair_e: _T2 = (0x671....0x673, .rightJoining)
private let __jt_rangePair_f: _T2 = (0x675....0x677, .rightJoining)
private let __jt_rangePair_g: _T2 = (0x678....0x687, .dualJoining)
private let __jt_rangePair_h: _T2 = (0x688....0x699, .rightJoining)
private let __jt_rangePair_i: _T2 = (0x69a....0x6bf, .dualJoining)
private let __jt_rangePair_j: _T2 = (0x6c1....0x6c2, .dualJoining)
private let __jt_rangePair_k: _T2 = (0x6c3....0x6cb, .rightJoining)
private let __jt_rangePair_l: _T2 = (0x6d0....0x6d1, .dualJoining)
private let __jt_rangePair_m: _T2 = (0x6d2....0x6d3, .rightJoining)
private let __jt_rangePair_n: _T2 = (0x6d6....0x6dc, .transparent)
private let __jt_rangePair_o: _T2 = (0x6df....0x6e4, .transparent)
private let __jt_rangePair_p: _T2 = (0x6e7....0x6e8, .transparent)
private let __jt_rangePair_q: _T2 = (0x6ea....0x6ed, .transparent)
private let __jt_rangePair_r: _T2 = (0x6ee....0x6ef, .rightJoining)
private let __jt_rangePair_s: _T2 = (0x6fa....0x6fc, .dualJoining)
private let __jt_rangePair_t: _T2 = (0x712....0x714, .dualJoining)
private let __jt_rangePair_u: _T2 = (0x715....0x719, .rightJoining)
private let __jt_rangePair_v: _T2 = (0x71a....0x71d, .dualJoining)
private let __jt_rangePair_w: _T2 = (0x71f....0x727, .dualJoining)
private let __jt_rangePair_x: _T2 = (0x72d....0x72e, .dualJoining)
private let __jt_rangePair_y: _T2 = (0x730....0x74a, .transparent)
private let __jt_rangePair_z: _T2 = (0x74e....0x758, .dualJoining)
private let __jt_rangePair_10: _T2 = (0x759....0x75b, .rightJoining)
private let __jt_rangePair_11: _T2 = (0x75c....0x76a, .dualJoining)
private let __jt_rangePair_12: _T2 = (0x76b....0x76c, .rightJoining)
private let __jt_rangePair_13: _T2 = (0x76d....0x770, .dualJoining)
private let __jt_rangePair_14: _T2 = (0x773....0x774, .rightJoining)
private let __jt_rangePair_15: _T2 = (0x775....0x777, .dualJoining)
private let __jt_rangePair_16: _T2 = (0x778....0x779, .rightJoining)
private let __jt_rangePair_17: _T2 = (0x77a....0x77f, .dualJoining)
private let __jt_rangePair_18: _T2 = (0x7a6....0x7b0, .transparent)
private let __jt_rangePair_19: _T2 = (0x7ca....0x7ea, .dualJoining)
private let __jt_rangePair_1a: _T2 = (0x7eb....0x7f3, .transparent)
private let __jt_rangePair_1b: _T2 = (0x816....0x819, .transparent)
private let __jt_rangePair_1c: _T2 = (0x81b....0x823, .transparent)
private let __jt_rangePair_1d: _T2 = (0x825....0x827, .transparent)
private let __jt_rangePair_1e: _T2 = (0x829....0x82d, .transparent)
private let __jt_rangePair_1f: _T2 = (0x841....0x845, .dualJoining)
private let __jt_rangePair_1g: _T2 = (0x846....0x847, .rightJoining)
private let __jt_rangePair_1h: _T2 = (0x84a....0x853, .dualJoining)
private let __jt_rangePair_1i: _T2 = (0x859....0x85b, .transparent)
private let __jt_rangePair_1j: _T2 = (0x862....0x865, .dualJoining)
private let __jt_rangePair_1k: _T2 = (0x869....0x86a, .rightJoining)
private let __jt_rangePair_1l: _T2 = (0x8a0....0x8a9, .dualJoining)
private let __jt_rangePair_1m: _T2 = (0x8aa....0x8ac, .rightJoining)
private let __jt_rangePair_1n: _T2 = (0x8af....0x8b0, .dualJoining)
private let __jt_rangePair_1o: _T2 = (0x8b1....0x8b2, .rightJoining)
private let __jt_rangePair_1p: _T2 = (0x8b3....0x8b4, .dualJoining)
private let __jt_rangePair_1q: _T2 = (0x8b6....0x8b8, .dualJoining)
private let __jt_rangePair_1r: _T2 = (0x8ba....0x8bd, .dualJoining)
private let __jt_rangePair_1s: _T2 = (0x8d3....0x8e1, .transparent)
private let __jt_rangePair_1t: _T2 = (0x8e3....0x902, .transparent)
private let __jt_rangePair_1u: _T2 = (0x941....0x948, .transparent)
private let __jt_rangePair_1v: _T2 = (0x951....0x957, .transparent)
private let __jt_rangePair_1w: _T2 = (0x962....0x963, .transparent)
private let __jt_rangePair_1x: _T2 = (0x9c1....0x9c4, .transparent)
private let __jt_rangePair_1y: _T2 = (0x9e2....0x9e3, .transparent)
private let __jt_rangePair_1z: _T2 = (0xa01....0xa02, .transparent)
private let __jt_rangePair_20: _T2 = (0xa41....0xa42, .transparent)
private let __jt_rangePair_21: _T2 = (0xa47....0xa48, .transparent)
private let __jt_rangePair_22: _T2 = (0xa4b....0xa4d, .transparent)
private let __jt_rangePair_23: _T2 = (0xa70....0xa71, .transparent)
private let __jt_rangePair_24: _T2 = (0xa81....0xa82, .transparent)
private let __jt_rangePair_25: _T2 = (0xac1....0xac5, .transparent)
private let __jt_rangePair_26: _T2 = (0xac7....0xac8, .transparent)
private let __jt_rangePair_27: _T2 = (0xae2....0xae3, .transparent)
private let __jt_rangePair_28: _T2 = (0xafa....0xaff, .transparent)
private let __jt_rangePair_29: _T2 = (0xb41....0xb44, .transparent)
private let __jt_rangePair_2a: _T2 = (0xb62....0xb63, .transparent)
private let __jt_rangePair_2b: _T2 = (0xc3e....0xc40, .transparent)
private let __jt_rangePair_2c: _T2 = (0xc46....0xc48, .transparent)
private let __jt_rangePair_2d: _T2 = (0xc4a....0xc4d, .transparent)
private let __jt_rangePair_2e: _T2 = (0xc55....0xc56, .transparent)
private let __jt_rangePair_2f: _T2 = (0xc62....0xc63, .transparent)
private let __jt_rangePair_2g: _T2 = (0xccc....0xccd, .transparent)
private let __jt_rangePair_2h: _T2 = (0xce2....0xce3, .transparent)
private let __jt_rangePair_2i: _T2 = (0xd00....0xd01, .transparent)
private let __jt_rangePair_2j: _T2 = (0xd3b....0xd3c, .transparent)
private let __jt_rangePair_2k: _T2 = (0xd41....0xd44, .transparent)
private let __jt_rangePair_2l: _T2 = (0xd62....0xd63, .transparent)
private let __jt_rangePair_2m: _T2 = (0xdd2....0xdd4, .transparent)
private let __jt_rangePair_2n: _T2 = (0xe34....0xe3a, .transparent)
private let __jt_rangePair_2o: _T2 = (0xe47....0xe4e, .transparent)
private let __jt_rangePair_2p: _T2 = (0xeb4....0xebc, .transparent)
private let __jt_rangePair_2q: _T2 = (0xec8....0xecd, .transparent)
private let __jt_rangePair_2r: _T2 = (0xf18....0xf19, .transparent)
private let __jt_rangePair_2s: _T2 = (0xf71....0xf7e, .transparent)
private let __jt_rangePair_2t: _T2 = (0xf80....0xf84, .transparent)
private let __jt_rangePair_2u: _T2 = (0xf86....0xf87, .transparent)
private let __jt_rangePair_2v: _T2 = (0xf8d....0xf97, .transparent)
private let __jt_rangePair_2w: _T2 = (0xf99....0xfbc, .transparent)
private let __jt_rangePair_2x: _T2 = (0x102d....0x1030, .transparent)
private let __jt_rangePair_2y: _T2 = (0x1032....0x1037, .transparent)
private let __jt_rangePair_2z: _T2 = (0x1039....0x103a, .transparent)
private let __jt_rangePair_30: _T2 = (0x103d....0x103e, .transparent)
private let __jt_rangePair_31: _T2 = (0x1058....0x1059, .transparent)
private let __jt_rangePair_32: _T2 = (0x105e....0x1060, .transparent)
private let __jt_rangePair_33: _T2 = (0x1071....0x1074, .transparent)
private let __jt_rangePair_34: _T2 = (0x1085....0x1086, .transparent)
private let __jt_rangePair_35: _T2 = (0x135d....0x135f, .transparent)
private let __jt_rangePair_36: _T2 = (0x1712....0x1714, .transparent)
private let __jt_rangePair_37: _T2 = (0x1732....0x1734, .transparent)
private let __jt_rangePair_38: _T2 = (0x1752....0x1753, .transparent)
private let __jt_rangePair_39: _T2 = (0x1772....0x1773, .transparent)
private let __jt_rangePair_3a: _T2 = (0x17b4....0x17b5, .transparent)
private let __jt_rangePair_3b: _T2 = (0x17b7....0x17bd, .transparent)
private let __jt_rangePair_3c: _T2 = (0x17c9....0x17d3, .transparent)
private let __jt_rangePair_3d: _T2 = (0x180b....0x180d, .transparent)
private let __jt_rangePair_3e: _T2 = (0x1820....0x1878, .dualJoining)
private let __jt_rangePair_3f: _T2 = (0x1885....0x1886, .transparent)
private let __jt_rangePair_3g: _T2 = (0x1887....0x18a8, .dualJoining)
private let __jt_rangePair_3h: _T2 = (0x1920....0x1922, .transparent)
private let __jt_rangePair_3i: _T2 = (0x1927....0x1928, .transparent)
private let __jt_rangePair_3j: _T2 = (0x1939....0x193b, .transparent)
private let __jt_rangePair_3k: _T2 = (0x1a17....0x1a18, .transparent)
private let __jt_rangePair_3l: _T2 = (0x1a58....0x1a5e, .transparent)
private let __jt_rangePair_3m: _T2 = (0x1a65....0x1a6c, .transparent)
private let __jt_rangePair_3n: _T2 = (0x1a73....0x1a7c, .transparent)
private let __jt_rangePair_3o: _T2 = (0x1ab0....0x1abe, .transparent)
private let __jt_rangePair_3p: _T2 = (0x1b00....0x1b03, .transparent)
private let __jt_rangePair_3q: _T2 = (0x1b36....0x1b3a, .transparent)
private let __jt_rangePair_3r: _T2 = (0x1b6b....0x1b73, .transparent)
private let __jt_rangePair_3s: _T2 = (0x1b80....0x1b81, .transparent)
private let __jt_rangePair_3t: _T2 = (0x1ba2....0x1ba5, .transparent)
private let __jt_rangePair_3u: _T2 = (0x1ba8....0x1ba9, .transparent)
private let __jt_rangePair_3v: _T2 = (0x1bab....0x1bad, .transparent)
private let __jt_rangePair_3w: _T2 = (0x1be8....0x1be9, .transparent)
private let __jt_rangePair_3x: _T2 = (0x1bef....0x1bf1, .transparent)
private let __jt_rangePair_3y: _T2 = (0x1c2c....0x1c33, .transparent)
private let __jt_rangePair_3z: _T2 = (0x1c36....0x1c37, .transparent)
private let __jt_rangePair_40: _T2 = (0x1cd0....0x1cd2, .transparent)
private let __jt_rangePair_41: _T2 = (0x1cd4....0x1ce0, .transparent)
private let __jt_rangePair_42: _T2 = (0x1ce2....0x1ce8, .transparent)
private let __jt_rangePair_43: _T2 = (0x1cf8....0x1cf9, .transparent)
private let __jt_rangePair_44: _T2 = (0x1dc0....0x1df9, .transparent)
private let __jt_rangePair_45: _T2 = (0x1dfb....0x1dff, .transparent)
private let __jt_rangePair_46: _T2 = (0x200e....0x200f, .transparent)
private let __jt_rangePair_47: _T2 = (0x202a....0x202e, .transparent)
private let __jt_rangePair_48: _T2 = (0x2060....0x2064, .transparent)
private let __jt_rangePair_49: _T2 = (0x206a....0x206f, .transparent)
private let __jt_rangePair_4a: _T2 = (0x20d0....0x20f0, .transparent)
private let __jt_rangePair_4b: _T2 = (0x2cef....0x2cf1, .transparent)
private let __jt_rangePair_4c: _T2 = (0x2de0....0x2dff, .transparent)
private let __jt_rangePair_4d: _T2 = (0x302a....0x302d, .transparent)
private let __jt_rangePair_4e: _T2 = (0x3099....0x309a, .transparent)
private let __jt_rangePair_4f: _T2 = (0xa66f....0xa672, .transparent)
private let __jt_rangePair_4g: _T2 = (0xa674....0xa67d, .transparent)
private let __jt_rangePair_4h: _T2 = (0xa69e....0xa69f, .transparent)
private let __jt_rangePair_4i: _T2 = (0xa6f0....0xa6f1, .transparent)
private let __jt_rangePair_4j: _T2 = (0xa825....0xa826, .transparent)
private let __jt_rangePair_4k: _T2 = (0xa840....0xa871, .dualJoining)
private let __jt_rangePair_4l: _T2 = (0xa8c4....0xa8c5, .transparent)
private let __jt_rangePair_4m: _T2 = (0xa8e0....0xa8f1, .transparent)
private let __jt_rangePair_4n: _T2 = (0xa926....0xa92d, .transparent)
private let __jt_rangePair_4o: _T2 = (0xa947....0xa951, .transparent)
private let __jt_rangePair_4p: _T2 = (0xa980....0xa982, .transparent)
private let __jt_rangePair_4q: _T2 = (0xa9b6....0xa9b9, .transparent)
private let __jt_rangePair_4r: _T2 = (0xa9bc....0xa9bd, .transparent)
private let __jt_rangePair_4s: _T2 = (0xaa29....0xaa2e, .transparent)
private let __jt_rangePair_4t: _T2 = (0xaa31....0xaa32, .transparent)
private let __jt_rangePair_4u: _T2 = (0xaa35....0xaa36, .transparent)
private let __jt_rangePair_4v: _T2 = (0xaab2....0xaab4, .transparent)
private let __jt_rangePair_4w: _T2 = (0xaab7....0xaab8, .transparent)
private let __jt_rangePair_4x: _T2 = (0xaabe....0xaabf, .transparent)
private let __jt_rangePair_4y: _T2 = (0xaaec....0xaaed, .transparent)
private let __jt_rangePair_4z: _T2 = (0xfe00....0xfe0f, .transparent)
private let __jt_rangePair_50: _T2 = (0xfe20....0xfe2f, .transparent)
private let __jt_rangePair_51: _T2 = (0xfff9....0xfffb, .transparent)
private let __jt_rangePair_52: _T2 = (0x10376....0x1037a, .transparent)
private let __jt_rangePair_53: _T2 = (0x10a01....0x10a03, .transparent)
private let __jt_rangePair_54: _T2 = (0x10a05....0x10a06, .transparent)
private let __jt_rangePair_55: _T2 = (0x10a0c....0x10a0f, .transparent)
private let __jt_rangePair_56: _T2 = (0x10a38....0x10a3a, .transparent)
private let __jt_rangePair_57: _T2 = (0x10ac0....0x10ac4, .dualJoining)
private let __jt_rangePair_58: _T2 = (0x10ac9....0x10aca, .rightJoining)
private let __jt_rangePair_59: _T2 = (0x10ace....0x10ad2, .rightJoining)
private let __jt_rangePair_5a: _T2 = (0x10ad3....0x10ad6, .dualJoining)
private let __jt_rangePair_5b: _T2 = (0x10ad8....0x10adc, .dualJoining)
private let __jt_rangePair_5c: _T2 = (0x10ade....0x10ae0, .dualJoining)
private let __jt_rangePair_5d: _T2 = (0x10ae5....0x10ae6, .transparent)
private let __jt_rangePair_5e: _T2 = (0x10aeb....0x10aee, .dualJoining)
private let __jt_rangePair_5f: _T2 = (0x10b83....0x10b85, .rightJoining)
private let __jt_rangePair_5g: _T2 = (0x10b86....0x10b88, .dualJoining)
private let __jt_rangePair_5h: _T2 = (0x10b8a....0x10b8b, .dualJoining)
private let __jt_rangePair_5i: _T2 = (0x10b8e....0x10b8f, .rightJoining)
private let __jt_rangePair_5j: _T2 = (0x10ba9....0x10bac, .rightJoining)
private let __jt_rangePair_5k: _T2 = (0x10bad....0x10bae, .dualJoining)
private let __jt_rangePair_5l: _T2 = (0x10d01....0x10d21, .dualJoining)
private let __jt_rangePair_5m: _T2 = (0x10d24....0x10d27, .transparent)
private let __jt_rangePair_5n: _T2 = (0x10f30....0x10f32, .dualJoining)
private let __jt_rangePair_5o: _T2 = (0x10f34....0x10f44, .dualJoining)
private let __jt_rangePair_5p: _T2 = (0x10f46....0x10f50, .transparent)
private let __jt_rangePair_5q: _T2 = (0x10f51....0x10f53, .dualJoining)
private let __jt_rangePair_5r: _T2 = (0x11038....0x11046, .transparent)
private let __jt_rangePair_5s: _T2 = (0x1107f....0x11081, .transparent)
private let __jt_rangePair_5t: _T2 = (0x110b3....0x110b6, .transparent)
private let __jt_rangePair_5u: _T2 = (0x110b9....0x110ba, .transparent)
private let __jt_rangePair_5v: _T2 = (0x11100....0x11102, .transparent)
private let __jt_rangePair_5w: _T2 = (0x11127....0x1112b, .transparent)
private let __jt_rangePair_5x: _T2 = (0x1112d....0x11134, .transparent)
private let __jt_rangePair_5y: _T2 = (0x11180....0x11181, .transparent)
private let __jt_rangePair_5z: _T2 = (0x111b6....0x111be, .transparent)
private let __jt_rangePair_60: _T2 = (0x111c9....0x111cc, .transparent)
private let __jt_rangePair_61: _T2 = (0x1122f....0x11231, .transparent)
private let __jt_rangePair_62: _T2 = (0x11236....0x11237, .transparent)
private let __jt_rangePair_63: _T2 = (0x112e3....0x112ea, .transparent)
private let __jt_rangePair_64: _T2 = (0x11300....0x11301, .transparent)
private let __jt_rangePair_65: _T2 = (0x1133b....0x1133c, .transparent)
private let __jt_rangePair_66: _T2 = (0x11366....0x1136c, .transparent)
private let __jt_rangePair_67: _T2 = (0x11370....0x11374, .transparent)
private let __jt_rangePair_68: _T2 = (0x11438....0x1143f, .transparent)
private let __jt_rangePair_69: _T2 = (0x11442....0x11444, .transparent)
private let __jt_rangePair_6a: _T2 = (0x114b3....0x114b8, .transparent)
private let __jt_rangePair_6b: _T2 = (0x114bf....0x114c0, .transparent)
private let __jt_rangePair_6c: _T2 = (0x114c2....0x114c3, .transparent)
private let __jt_rangePair_6d: _T2 = (0x115b2....0x115b5, .transparent)
private let __jt_rangePair_6e: _T2 = (0x115bc....0x115bd, .transparent)
private let __jt_rangePair_6f: _T2 = (0x115bf....0x115c0, .transparent)
private let __jt_rangePair_6g: _T2 = (0x115dc....0x115dd, .transparent)
private let __jt_rangePair_6h: _T2 = (0x11633....0x1163a, .transparent)
private let __jt_rangePair_6i: _T2 = (0x1163f....0x11640, .transparent)
private let __jt_rangePair_6j: _T2 = (0x116b0....0x116b5, .transparent)
private let __jt_rangePair_6k: _T2 = (0x1171d....0x1171f, .transparent)
private let __jt_rangePair_6l: _T2 = (0x11722....0x11725, .transparent)
private let __jt_rangePair_6m: _T2 = (0x11727....0x1172b, .transparent)
private let __jt_rangePair_6n: _T2 = (0x1182f....0x11837, .transparent)
private let __jt_rangePair_6o: _T2 = (0x11839....0x1183a, .transparent)
private let __jt_rangePair_6p: _T2 = (0x119d4....0x119d7, .transparent)
private let __jt_rangePair_6q: _T2 = (0x119da....0x119db, .transparent)
private let __jt_rangePair_6r: _T2 = (0x11a01....0x11a0a, .transparent)
private let __jt_rangePair_6s: _T2 = (0x11a33....0x11a38, .transparent)
private let __jt_rangePair_6t: _T2 = (0x11a3b....0x11a3e, .transparent)
private let __jt_rangePair_6u: _T2 = (0x11a51....0x11a56, .transparent)
private let __jt_rangePair_6v: _T2 = (0x11a59....0x11a5b, .transparent)
private let __jt_rangePair_6w: _T2 = (0x11a8a....0x11a96, .transparent)
private let __jt_rangePair_6x: _T2 = (0x11a98....0x11a99, .transparent)
private let __jt_rangePair_6y: _T2 = (0x11c30....0x11c36, .transparent)
private let __jt_rangePair_6z: _T2 = (0x11c38....0x11c3d, .transparent)
private let __jt_rangePair_70: _T2 = (0x11c92....0x11ca7, .transparent)
private let __jt_rangePair_71: _T2 = (0x11caa....0x11cb0, .transparent)
private let __jt_rangePair_72: _T2 = (0x11cb2....0x11cb3, .transparent)
private let __jt_rangePair_73: _T2 = (0x11cb5....0x11cb6, .transparent)
private let __jt_rangePair_74: _T2 = (0x11d31....0x11d36, .transparent)
private let __jt_rangePair_75: _T2 = (0x11d3c....0x11d3d, .transparent)
private let __jt_rangePair_76: _T2 = (0x11d3f....0x11d45, .transparent)
private let __jt_rangePair_77: _T2 = (0x11d90....0x11d91, .transparent)
private let __jt_rangePair_78: _T2 = (0x11ef3....0x11ef4, .transparent)
private let __jt_rangePair_79: _T2 = (0x13430....0x13438, .transparent)
private let __jt_rangePair_7a: _T2 = (0x16af0....0x16af4, .transparent)
private let __jt_rangePair_7b: _T2 = (0x16b30....0x16b36, .transparent)
private let __jt_rangePair_7c: _T2 = (0x16f8f....0x16f92, .transparent)
private let __jt_rangePair_7d: _T2 = (0x1bc9d....0x1bc9e, .transparent)
private let __jt_rangePair_7e: _T2 = (0x1bca0....0x1bca3, .transparent)
private let __jt_rangePair_7f: _T2 = (0x1d167....0x1d169, .transparent)
private let __jt_rangePair_7g: _T2 = (0x1d173....0x1d182, .transparent)
private let __jt_rangePair_7h: _T2 = (0x1d185....0x1d18b, .transparent)
private let __jt_rangePair_7i: _T2 = (0x1d1aa....0x1d1ad, .transparent)
private let __jt_rangePair_7j: _T2 = (0x1d242....0x1d244, .transparent)
private let __jt_rangePair_7k: _T2 = (0x1da00....0x1da36, .transparent)
private let __jt_rangePair_7l: _T2 = (0x1da3b....0x1da6c, .transparent)
private let __jt_rangePair_7m: _T2 = (0x1da9b....0x1da9f, .transparent)
private let __jt_rangePair_7n: _T2 = (0x1daa1....0x1daaf, .transparent)
private let __jt_rangePair_7o: _T2 = (0x1e000....0x1e006, .transparent)
private let __jt_rangePair_7p: _T2 = (0x1e008....0x1e018, .transparent)
private let __jt_rangePair_7q: _T2 = (0x1e01b....0x1e021, .transparent)
private let __jt_rangePair_7r: _T2 = (0x1e023....0x1e024, .transparent)
private let __jt_rangePair_7s: _T2 = (0x1e026....0x1e02a, .transparent)
private let __jt_rangePair_7t: _T2 = (0x1e130....0x1e136, .transparent)
private let __jt_rangePair_7u: _T2 = (0x1e2ec....0x1e2ef, .transparent)
private let __jt_rangePair_7v: _T2 = (0x1e8d0....0x1e8d6, .transparent)
private let __jt_rangePair_7w: _T2 = (0x1e900....0x1e943, .dualJoining)
private let __jt_rangePair_7x: _T2 = (0x1e944....0x1e94b, .transparent)
private let __jt_rangePair_7y: _T2 = (0xe0020....0xe007f, .transparent)
private let __jt_rangePair_7z: _T2 = (0xe0100....0xe01ef, .transparent)
private let __jt_rangePairArray: _T3 = [
  __jt_rangePair_0,
  __jt_rangePair_1,
  __jt_rangePair_2,
  __jt_rangePair_3,
  __jt_rangePair_4,
  __jt_rangePair_5,
  __jt_rangePair_6,
  __jt_rangePair_7,
  __jt_rangePair_8,
  __jt_rangePair_9,
  __jt_rangePair_a,
  __jt_rangePair_b,
  __jt_rangePair_c,
  __jt_rangePair_d,
  __jt_rangePair_e,
  __jt_rangePair_f,
  __jt_rangePair_g,
  __jt_rangePair_h,
  __jt_rangePair_i,
  __jt_rangePair_j,
  __jt_rangePair_k,
  __jt_rangePair_l,
  __jt_rangePair_m,
  __jt_rangePair_n,
  __jt_rangePair_o,
  __jt_rangePair_p,
  __jt_rangePair_q,
  __jt_rangePair_r,
  __jt_rangePair_s,
  __jt_rangePair_t,
  __jt_rangePair_u,
  __jt_rangePair_v,
  __jt_rangePair_w,
  __jt_rangePair_x,
  __jt_rangePair_y,
  __jt_rangePair_z,
  __jt_rangePair_10,
  __jt_rangePair_11,
  __jt_rangePair_12,
  __jt_rangePair_13,
  __jt_rangePair_14,
  __jt_rangePair_15,
  __jt_rangePair_16,
  __jt_rangePair_17,
  __jt_rangePair_18,
  __jt_rangePair_19,
  __jt_rangePair_1a,
  __jt_rangePair_1b,
  __jt_rangePair_1c,
  __jt_rangePair_1d,
  __jt_rangePair_1e,
  __jt_rangePair_1f,
  __jt_rangePair_1g,
  __jt_rangePair_1h,
  __jt_rangePair_1i,
  __jt_rangePair_1j,
  __jt_rangePair_1k,
  __jt_rangePair_1l,
  __jt_rangePair_1m,
  __jt_rangePair_1n,
  __jt_rangePair_1o,
  __jt_rangePair_1p,
  __jt_rangePair_1q,
  __jt_rangePair_1r,
  __jt_rangePair_1s,
  __jt_rangePair_1t,
  __jt_rangePair_1u,
  __jt_rangePair_1v,
  __jt_rangePair_1w,
  __jt_rangePair_1x,
  __jt_rangePair_1y,
  __jt_rangePair_1z,
  __jt_rangePair_20,
  __jt_rangePair_21,
  __jt_rangePair_22,
  __jt_rangePair_23,
  __jt_rangePair_24,
  __jt_rangePair_25,
  __jt_rangePair_26,
  __jt_rangePair_27,
  __jt_rangePair_28,
  __jt_rangePair_29,
  __jt_rangePair_2a,
  __jt_rangePair_2b,
  __jt_rangePair_2c,
  __jt_rangePair_2d,
  __jt_rangePair_2e,
  __jt_rangePair_2f,
  __jt_rangePair_2g,
  __jt_rangePair_2h,
  __jt_rangePair_2i,
  __jt_rangePair_2j,
  __jt_rangePair_2k,
  __jt_rangePair_2l,
  __jt_rangePair_2m,
  __jt_rangePair_2n,
  __jt_rangePair_2o,
  __jt_rangePair_2p,
  __jt_rangePair_2q,
  __jt_rangePair_2r,
  __jt_rangePair_2s,
  __jt_rangePair_2t,
  __jt_rangePair_2u,
  __jt_rangePair_2v,
  __jt_rangePair_2w,
  __jt_rangePair_2x,
  __jt_rangePair_2y,
  __jt_rangePair_2z,
  __jt_rangePair_30,
  __jt_rangePair_31,
  __jt_rangePair_32,
  __jt_rangePair_33,
  __jt_rangePair_34,
  __jt_rangePair_35,
  __jt_rangePair_36,
  __jt_rangePair_37,
  __jt_rangePair_38,
  __jt_rangePair_39,
  __jt_rangePair_3a,
  __jt_rangePair_3b,
  __jt_rangePair_3c,
  __jt_rangePair_3d,
  __jt_rangePair_3e,
  __jt_rangePair_3f,
  __jt_rangePair_3g,
  __jt_rangePair_3h,
  __jt_rangePair_3i,
  __jt_rangePair_3j,
  __jt_rangePair_3k,
  __jt_rangePair_3l,
  __jt_rangePair_3m,
  __jt_rangePair_3n,
  __jt_rangePair_3o,
  __jt_rangePair_3p,
  __jt_rangePair_3q,
  __jt_rangePair_3r,
  __jt_rangePair_3s,
  __jt_rangePair_3t,
  __jt_rangePair_3u,
  __jt_rangePair_3v,
  __jt_rangePair_3w,
  __jt_rangePair_3x,
  __jt_rangePair_3y,
  __jt_rangePair_3z,
  __jt_rangePair_40,
  __jt_rangePair_41,
  __jt_rangePair_42,
  __jt_rangePair_43,
  __jt_rangePair_44,
  __jt_rangePair_45,
  __jt_rangePair_46,
  __jt_rangePair_47,
  __jt_rangePair_48,
  __jt_rangePair_49,
  __jt_rangePair_4a,
  __jt_rangePair_4b,
  __jt_rangePair_4c,
  __jt_rangePair_4d,
  __jt_rangePair_4e,
  __jt_rangePair_4f,
  __jt_rangePair_4g,
  __jt_rangePair_4h,
  __jt_rangePair_4i,
  __jt_rangePair_4j,
  __jt_rangePair_4k,
  __jt_rangePair_4l,
  __jt_rangePair_4m,
  __jt_rangePair_4n,
  __jt_rangePair_4o,
  __jt_rangePair_4p,
  __jt_rangePair_4q,
  __jt_rangePair_4r,
  __jt_rangePair_4s,
  __jt_rangePair_4t,
  __jt_rangePair_4u,
  __jt_rangePair_4v,
  __jt_rangePair_4w,
  __jt_rangePair_4x,
  __jt_rangePair_4y,
  __jt_rangePair_4z,
  __jt_rangePair_50,
  __jt_rangePair_51,
  __jt_rangePair_52,
  __jt_rangePair_53,
  __jt_rangePair_54,
  __jt_rangePair_55,
  __jt_rangePair_56,
  __jt_rangePair_57,
  __jt_rangePair_58,
  __jt_rangePair_59,
  __jt_rangePair_5a,
  __jt_rangePair_5b,
  __jt_rangePair_5c,
  __jt_rangePair_5d,
  __jt_rangePair_5e,
  __jt_rangePair_5f,
  __jt_rangePair_5g,
  __jt_rangePair_5h,
  __jt_rangePair_5i,
  __jt_rangePair_5j,
  __jt_rangePair_5k,
  __jt_rangePair_5l,
  __jt_rangePair_5m,
  __jt_rangePair_5n,
  __jt_rangePair_5o,
  __jt_rangePair_5p,
  __jt_rangePair_5q,
  __jt_rangePair_5r,
  __jt_rangePair_5s,
  __jt_rangePair_5t,
  __jt_rangePair_5u,
  __jt_rangePair_5v,
  __jt_rangePair_5w,
  __jt_rangePair_5x,
  __jt_rangePair_5y,
  __jt_rangePair_5z,
  __jt_rangePair_60,
  __jt_rangePair_61,
  __jt_rangePair_62,
  __jt_rangePair_63,
  __jt_rangePair_64,
  __jt_rangePair_65,
  __jt_rangePair_66,
  __jt_rangePair_67,
  __jt_rangePair_68,
  __jt_rangePair_69,
  __jt_rangePair_6a,
  __jt_rangePair_6b,
  __jt_rangePair_6c,
  __jt_rangePair_6d,
  __jt_rangePair_6e,
  __jt_rangePair_6f,
  __jt_rangePair_6g,
  __jt_rangePair_6h,
  __jt_rangePair_6i,
  __jt_rangePair_6j,
  __jt_rangePair_6k,
  __jt_rangePair_6l,
  __jt_rangePair_6m,
  __jt_rangePair_6n,
  __jt_rangePair_6o,
  __jt_rangePair_6p,
  __jt_rangePair_6q,
  __jt_rangePair_6r,
  __jt_rangePair_6s,
  __jt_rangePair_6t,
  __jt_rangePair_6u,
  __jt_rangePair_6v,
  __jt_rangePair_6w,
  __jt_rangePair_6x,
  __jt_rangePair_6y,
  __jt_rangePair_6z,
  __jt_rangePair_70,
  __jt_rangePair_71,
  __jt_rangePair_72,
  __jt_rangePair_73,
  __jt_rangePair_74,
  __jt_rangePair_75,
  __jt_rangePair_76,
  __jt_rangePair_77,
  __jt_rangePair_78,
  __jt_rangePair_79,
  __jt_rangePair_7a,
  __jt_rangePair_7b,
  __jt_rangePair_7c,
  __jt_rangePair_7d,
  __jt_rangePair_7e,
  __jt_rangePair_7f,
  __jt_rangePair_7g,
  __jt_rangePair_7h,
  __jt_rangePair_7i,
  __jt_rangePair_7j,
  __jt_rangePair_7k,
  __jt_rangePair_7l,
  __jt_rangePair_7m,
  __jt_rangePair_7n,
  __jt_rangePair_7o,
  __jt_rangePair_7p,
  __jt_rangePair_7q,
  __jt_rangePair_7r,
  __jt_rangePair_7s,
  __jt_rangePair_7t,
  __jt_rangePair_7u,
  __jt_rangePair_7v,
  __jt_rangePair_7w,
  __jt_rangePair_7x,
  __jt_rangePair_7y,
  __jt_rangePair_7z,
]
private let __jt_rangeDictionary = RangeDictionary<Unicode.Scalar.Value, _T0>(carefullySortedRangesAndValues: __jt_rangePairArray)
internal let _jt = UnicodeScalarValueDictionary<Unicode.JoiningType>(dictionary: __jt_dictionary, rangeDictionary: __jt_rangeDictionary)
