//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://www.unicode.org/Public/UCD/latest/ucd/extracted/DerivedBinaryProperties.txt
// Last-Modified: 2019-09-10T19:51:21Z
// ETag: "9f8036-41e9-592383a826040"

/*
  UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE
  
  See <a href="https://www.unicode.org/copyright.html">Terms of Use</a> for definitions of Unicode Inc.'s
  Data Files and Software.
  NOTICE TO USER: Carefully read the following legal agreement.
  BY DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S
  DATA FILES ("DATA FILES"), AND/OR SOFTWARE ("SOFTWARE"),
  YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
  TERMS AND CONDITIONS OF THIS AGREEMENT.
  IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE
  THE DATA FILES OR SOFTWARE.
  COPYRIGHT AND PERMISSION NOTICE
  Copyright © 1991-2020 Unicode, Inc. All rights reserved.
  Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
  Permission is hereby granted, free of charge, to any person obtaining
  a copy of the Unicode data files and any associated documentation
  (the "Data Files") or Unicode software and any associated documentation
  (the "Software") to deal in the Data Files or Software
  without restriction, including without limitation the rights to use,
  copy, modify, merge, publish, distribute, and/or sell copies of
  the Data Files or Software, and to permit persons to whom the Data Files
  or Software are furnished to do so, provided that either
  (a) this copyright and permission notice appear with all copies
  of the Data Files or Software, or
  (b) this copyright and permission notice appear in associated
  Documentation.
  THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
  ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT OF THIRD PARTY RIGHTS.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
  NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
  DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
  DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
  TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
  PERFORMANCE OF THE DATA FILES OR SOFTWARE.
  Except as contained in this notice, the name of a copyright holder
  shall not be used in advertising or otherwise to promote the sale,
  use or other dealings in these Data Files or Software without prior
  written authorization of the copyright holder.
*/

// Required Modules
import Ranges

// Type Aliases
private typealias _T0 = Unicode.Scalar.Value
private typealias _T1 = Set<_T0>
private typealias _T2 = AnyRange<_T0>
private typealias _T3 = Array<_T2>

private let __binProp_Bidi_Mirrored_set: _T1 = [
  0x28,
  0x29,
  0x3c,
  0x3e,
  0x5b,
  0x5d,
  0x7b,
  0x7d,
  0xab,
  0xbb,
  0xf3a,
  0xf3b,
  0xf3c,
  0xf3d,
  0x169b,
  0x169c,
  0x2039,
  0x203a,
  0x2045,
  0x2046,
  0x207d,
  0x207e,
  0x208d,
  0x208e,
  0x2140,
  0x2201,
  0x2202,
  0x2203,
  0x2204,
  0x2211,
  0x2215,
  0x2216,
  0x221a,
  0x221b,
  0x221c,
  0x221d,
  0x221f,
  0x2220,
  0x2221,
  0x2222,
  0x2224,
  0x2226,
  0x2239,
  0x2252,
  0x2253,
  0x2254,
  0x2255,
  0x225f,
  0x2260,
  0x2262,
  0x228f,
  0x2290,
  0x2291,
  0x2292,
  0x2298,
  0x22a2,
  0x22a3,
  0x22be,
  0x22bf,
  0x22d0,
  0x22d1,
  0x2308,
  0x2309,
  0x230a,
  0x230b,
  0x2320,
  0x2321,
  0x2329,
  0x232a,
  0x27c0,
  0x27c3,
  0x27c4,
  0x27c5,
  0x27c6,
  0x27c8,
  0x27c9,
  0x27cb,
  0x27cc,
  0x27cd,
  0x27d3,
  0x27d4,
  0x27d5,
  0x27d6,
  0x27dc,
  0x27dd,
  0x27de,
  0x29b8,
  0x29c9,
  0x29d4,
  0x29d5,
  0x29e1,
  0x29e3,
  0x29e4,
  0x29e5,
  0x29e8,
  0x29e9,
  0x29fc,
  0x29fd,
  0x2a1e,
  0x2a1f,
  0x2a20,
  0x2a21,
  0x2a24,
  0x2a26,
  0x2a29,
  0x2a2b,
  0x2a2c,
  0x2a2d,
  0x2a2e,
  0x2a34,
  0x2a35,
  0x2a3c,
  0x2a3d,
  0x2a3e,
  0x2a57,
  0x2a58,
  0x2a64,
  0x2a65,
  0x2a6a,
  0x2a6b,
  0x2a6c,
  0x2a6d,
  0x2a6f,
  0x2a70,
  0x2a73,
  0x2a74,
  0x2adc,
  0x2ade,
  0x2aec,
  0x2aed,
  0x2aee,
  0x2af3,
  0x2afd,
  0x2bfe,
  0x2e02,
  0x2e03,
  0x2e04,
  0x2e05,
  0x2e09,
  0x2e0a,
  0x2e0c,
  0x2e0d,
  0x2e1c,
  0x2e1d,
  0xfe64,
  0xfe65,
  0xff08,
  0xff09,
  0xff1c,
  0xff1e,
  0xff3b,
  0xff3d,
  0xff5b,
  0xff5d,
  0xff5f,
  0xff60,
  0xff62,
  0xff63,
  0x1d6db,
  0x1d715,
  0x1d74f,
  0x1d789,
  0x1d7c3,
]
private let __binProp_Bidi_Mirrored_range_0: _T2 = 0x2208....0x220d
private let __binProp_Bidi_Mirrored_range_1: _T2 = 0x222b....0x2233
private let __binProp_Bidi_Mirrored_range_2: _T2 = 0x223b....0x224c
private let __binProp_Bidi_Mirrored_range_3: _T2 = 0x2264....0x226b
private let __binProp_Bidi_Mirrored_range_4: _T2 = 0x226e....0x228c
private let __binProp_Bidi_Mirrored_range_5: _T2 = 0x22a6....0x22b8
private let __binProp_Bidi_Mirrored_range_6: _T2 = 0x22c9....0x22cd
private let __binProp_Bidi_Mirrored_range_7: _T2 = 0x22d6....0x22ed
private let __binProp_Bidi_Mirrored_range_8: _T2 = 0x22f0....0x22ff
private let __binProp_Bidi_Mirrored_range_9: _T2 = 0x2768....0x2775
private let __binProp_Bidi_Mirrored_range_a: _T2 = 0x27e2....0x27ef
private let __binProp_Bidi_Mirrored_range_b: _T2 = 0x2983....0x2998
private let __binProp_Bidi_Mirrored_range_c: _T2 = 0x299b....0x29a0
private let __binProp_Bidi_Mirrored_range_d: _T2 = 0x29a2....0x29af
private let __binProp_Bidi_Mirrored_range_e: _T2 = 0x29c0....0x29c5
private let __binProp_Bidi_Mirrored_range_f: _T2 = 0x29ce....0x29d2
private let __binProp_Bidi_Mirrored_range_g: _T2 = 0x29d8....0x29dc
private let __binProp_Bidi_Mirrored_range_h: _T2 = 0x29f4....0x29f9
private let __binProp_Bidi_Mirrored_range_i: _T2 = 0x2a0a....0x2a1c
private let __binProp_Bidi_Mirrored_range_j: _T2 = 0x2a79....0x2aa3
private let __binProp_Bidi_Mirrored_range_k: _T2 = 0x2aa6....0x2aad
private let __binProp_Bidi_Mirrored_range_l: _T2 = 0x2aaf....0x2ad6
private let __binProp_Bidi_Mirrored_range_m: _T2 = 0x2ae2....0x2ae6
private let __binProp_Bidi_Mirrored_range_n: _T2 = 0x2af7....0x2afb
private let __binProp_Bidi_Mirrored_range_o: _T2 = 0x2e20....0x2e29
private let __binProp_Bidi_Mirrored_range_p: _T2 = 0x3008....0x3011
private let __binProp_Bidi_Mirrored_range_q: _T2 = 0x3014....0x301b
private let __binProp_Bidi_Mirrored_range_r: _T2 = 0xfe59....0xfe5e
private let __binProp_Bidi_Mirrored_array: _T3 = [
  __binProp_Bidi_Mirrored_range_0,
  __binProp_Bidi_Mirrored_range_1,
  __binProp_Bidi_Mirrored_range_2,
  __binProp_Bidi_Mirrored_range_3,
  __binProp_Bidi_Mirrored_range_4,
  __binProp_Bidi_Mirrored_range_5,
  __binProp_Bidi_Mirrored_range_6,
  __binProp_Bidi_Mirrored_range_7,
  __binProp_Bidi_Mirrored_range_8,
  __binProp_Bidi_Mirrored_range_9,
  __binProp_Bidi_Mirrored_range_a,
  __binProp_Bidi_Mirrored_range_b,
  __binProp_Bidi_Mirrored_range_c,
  __binProp_Bidi_Mirrored_range_d,
  __binProp_Bidi_Mirrored_range_e,
  __binProp_Bidi_Mirrored_range_f,
  __binProp_Bidi_Mirrored_range_g,
  __binProp_Bidi_Mirrored_range_h,
  __binProp_Bidi_Mirrored_range_i,
  __binProp_Bidi_Mirrored_range_j,
  __binProp_Bidi_Mirrored_range_k,
  __binProp_Bidi_Mirrored_range_l,
  __binProp_Bidi_Mirrored_range_m,
  __binProp_Bidi_Mirrored_range_n,
  __binProp_Bidi_Mirrored_range_o,
  __binProp_Bidi_Mirrored_range_p,
  __binProp_Bidi_Mirrored_range_q,
  __binProp_Bidi_Mirrored_range_r,
]
private let __binProp_Bidi_Mirrored_ranges = MultipleRanges<Unicode.Scalar.Value>(carefullySortedRanges: __binProp_Bidi_Mirrored_array)
internal let _binProp_Bidi_Mirrored = UnicodeScalarValueSet(singleValues: __binProp_Bidi_Mirrored_set, ranges: __binProp_Bidi_Mirrored_ranges)
