//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: https://unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt
// Last-Modified: 2021-08-26T19:49:15Z
// ETag: "1ab54-5ca7ba96b89a1-gzip"

/*
  UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE
  
  See <a href="https://www.unicode.org/copyright.html">Terms of Use</a> for definitions of Unicode Inc.'s
  Data Files and Software.
  NOTICE TO USER: Carefully read the following legal agreement.
  BY DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S
  DATA FILES ("DATA FILES"), AND/OR SOFTWARE ("SOFTWARE"),
  YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
  TERMS AND CONDITIONS OF THIS AGREEMENT.
  IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE
  THE DATA FILES OR SOFTWARE.
  COPYRIGHT AND PERMISSION NOTICE
  Copyright © 1991-2021 Unicode, Inc. All rights reserved.
  Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
  Permission is hereby granted, free of charge, to any person obtaining
  a copy of the Unicode data files and any associated documentation
  (the "Data Files") or Unicode software and any associated documentation
  (the "Software") to deal in the Data Files or Software
  without restriction, including without limitation the rights to use,
  copy, modify, merge, publish, distribute, and/or sell copies of
  the Data Files or Software, and to permit persons to whom the Data Files
  or Software are furnished to do so, provided that either
  (a) this copyright and permission notice appear with all copies
  of the Data Files or Software, or
  (b) this copyright and permission notice appear in associated
  Documentation.
  THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
  ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT OF THIRD PARTY RIGHTS.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
  NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
  DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
  DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
  TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
  PERFORMANCE OF THE DATA FILES OR SOFTWARE.
  Except as contained in this notice, the name of a copyright holder
  shall not be used in advertising or otherwise to promote the sale,
  use or other dealings in these Data Files or Software without prior
  written authorization of the copyright holder.
*/

// Required Modules
import Ranges

// Type Aliases
private typealias _T0 = Unicode.Scalar.Value
private typealias _T1 = Set<_T0>
private typealias _T2 = AnyRange<_T0>
private typealias _T3 = Array<_T2>

/* ********************************************************************************************** */
// Emoji Property: Emoji
private let __emoji_Emoji_set: _T1 = [
  0x23,
  0x2a,
  0xa9,
  0xae,
  0x203c,
  0x2049,
  0x2122,
  0x2139,
  0x21a9,
  0x21aa,
  0x231a,
  0x231b,
  0x2328,
  0x23cf,
  0x23f8,
  0x23f9,
  0x23fa,
  0x24c2,
  0x25aa,
  0x25ab,
  0x25b6,
  0x25c0,
  0x25fb,
  0x25fc,
  0x25fd,
  0x25fe,
  0x260e,
  0x2611,
  0x2614,
  0x2615,
  0x2618,
  0x261d,
  0x2620,
  0x2622,
  0x2623,
  0x2626,
  0x262a,
  0x262e,
  0x262f,
  0x2638,
  0x2639,
  0x263a,
  0x2640,
  0x2642,
  0x265f,
  0x2660,
  0x2663,
  0x2665,
  0x2666,
  0x2668,
  0x267b,
  0x267e,
  0x267f,
  0x2699,
  0x269b,
  0x269c,
  0x26a0,
  0x26a1,
  0x26a7,
  0x26aa,
  0x26ab,
  0x26b0,
  0x26b1,
  0x26bd,
  0x26be,
  0x26c4,
  0x26c5,
  0x26c8,
  0x26ce,
  0x26cf,
  0x26d1,
  0x26d3,
  0x26d4,
  0x26e9,
  0x26ea,
  0x26f7,
  0x26f8,
  0x26f9,
  0x26fa,
  0x26fd,
  0x2702,
  0x2705,
  0x270f,
  0x2712,
  0x2714,
  0x2716,
  0x271d,
  0x2721,
  0x2728,
  0x2733,
  0x2734,
  0x2744,
  0x2747,
  0x274c,
  0x274e,
  0x2753,
  0x2754,
  0x2755,
  0x2757,
  0x2763,
  0x2764,
  0x2795,
  0x2796,
  0x2797,
  0x27a1,
  0x27b0,
  0x27bf,
  0x2934,
  0x2935,
  0x2b05,
  0x2b06,
  0x2b07,
  0x2b1b,
  0x2b1c,
  0x2b50,
  0x2b55,
  0x3030,
  0x303d,
  0x3297,
  0x3299,
  0x1f004,
  0x1f0cf,
  0x1f170,
  0x1f171,
  0x1f17e,
  0x1f17f,
  0x1f18e,
  0x1f201,
  0x1f202,
  0x1f21a,
  0x1f22f,
  0x1f250,
  0x1f251,
  0x1f396,
  0x1f397,
  0x1f399,
  0x1f39a,
  0x1f39b,
  0x1f3f3,
  0x1f3f4,
  0x1f3f5,
  0x1f56f,
  0x1f570,
  0x1f587,
  0x1f58a,
  0x1f58b,
  0x1f58c,
  0x1f58d,
  0x1f590,
  0x1f595,
  0x1f596,
  0x1f5a4,
  0x1f5a5,
  0x1f5a8,
  0x1f5b1,
  0x1f5b2,
  0x1f5bc,
  0x1f5c2,
  0x1f5c3,
  0x1f5c4,
  0x1f5d1,
  0x1f5d2,
  0x1f5d3,
  0x1f5dc,
  0x1f5dd,
  0x1f5de,
  0x1f5e1,
  0x1f5e3,
  0x1f5e8,
  0x1f5ef,
  0x1f5f3,
  0x1f6d5,
  0x1f6d6,
  0x1f6d7,
  0x1f6e9,
  0x1f6eb,
  0x1f6ec,
  0x1f6f0,
  0x1f7f0,
]
private let __emoji_Emoji_range_0: _T2 = 0x30....0x39
private let __emoji_Emoji_range_1: _T2 = 0x2194....0x2199
private let __emoji_Emoji_range_2: _T2 = 0x23e9....0x23f3
private let __emoji_Emoji_range_3: _T2 = 0x2600....0x2604
private let __emoji_Emoji_range_4: _T2 = 0x2648....0x2653
private let __emoji_Emoji_range_5: _T2 = 0x2692....0x2697
private let __emoji_Emoji_range_6: _T2 = 0x26f0....0x26f5
private let __emoji_Emoji_range_7: _T2 = 0x2708....0x270d
private let __emoji_Emoji_range_8: _T2 = 0x1f191....0x1f19a
private let __emoji_Emoji_range_9: _T2 = 0x1f1e6....0x1f1ff
private let __emoji_Emoji_range_a: _T2 = 0x1f232....0x1f23a
private let __emoji_Emoji_range_b: _T2 = 0x1f300....0x1f321
private let __emoji_Emoji_range_c: _T2 = 0x1f324....0x1f393
private let __emoji_Emoji_range_d: _T2 = 0x1f39e....0x1f3f0
private let __emoji_Emoji_range_e: _T2 = 0x1f3f7....0x1f4fd
private let __emoji_Emoji_range_f: _T2 = 0x1f4ff....0x1f53d
private let __emoji_Emoji_range_g: _T2 = 0x1f549....0x1f54e
private let __emoji_Emoji_range_h: _T2 = 0x1f550....0x1f567
private let __emoji_Emoji_range_i: _T2 = 0x1f573....0x1f57a
private let __emoji_Emoji_range_j: _T2 = 0x1f5fa....0x1f64f
private let __emoji_Emoji_range_k: _T2 = 0x1f680....0x1f6c5
private let __emoji_Emoji_range_l: _T2 = 0x1f6cb....0x1f6d2
private let __emoji_Emoji_range_m: _T2 = 0x1f6dd....0x1f6e5
private let __emoji_Emoji_range_n: _T2 = 0x1f6f3....0x1f6fc
private let __emoji_Emoji_range_o: _T2 = 0x1f7e0....0x1f7eb
private let __emoji_Emoji_range_p: _T2 = 0x1f90c....0x1f93a
private let __emoji_Emoji_range_q: _T2 = 0x1f93c....0x1f945
private let __emoji_Emoji_range_r: _T2 = 0x1f947....0x1f9ff
private let __emoji_Emoji_range_s: _T2 = 0x1fa70....0x1fa74
private let __emoji_Emoji_range_t: _T2 = 0x1fa78....0x1fa7c
private let __emoji_Emoji_range_u: _T2 = 0x1fa80....0x1fa86
private let __emoji_Emoji_range_v: _T2 = 0x1fa90....0x1faac
private let __emoji_Emoji_range_w: _T2 = 0x1fab0....0x1faba
private let __emoji_Emoji_range_x: _T2 = 0x1fac0....0x1fac5
private let __emoji_Emoji_range_y: _T2 = 0x1fad0....0x1fad9
private let __emoji_Emoji_range_z: _T2 = 0x1fae0....0x1fae7
private let __emoji_Emoji_range_10: _T2 = 0x1faf0....0x1faf6
private let __emoji_Emoji_array: _T3 = [
  __emoji_Emoji_range_0,
  __emoji_Emoji_range_1,
  __emoji_Emoji_range_2,
  __emoji_Emoji_range_3,
  __emoji_Emoji_range_4,
  __emoji_Emoji_range_5,
  __emoji_Emoji_range_6,
  __emoji_Emoji_range_7,
  __emoji_Emoji_range_8,
  __emoji_Emoji_range_9,
  __emoji_Emoji_range_a,
  __emoji_Emoji_range_b,
  __emoji_Emoji_range_c,
  __emoji_Emoji_range_d,
  __emoji_Emoji_range_e,
  __emoji_Emoji_range_f,
  __emoji_Emoji_range_g,
  __emoji_Emoji_range_h,
  __emoji_Emoji_range_i,
  __emoji_Emoji_range_j,
  __emoji_Emoji_range_k,
  __emoji_Emoji_range_l,
  __emoji_Emoji_range_m,
  __emoji_Emoji_range_n,
  __emoji_Emoji_range_o,
  __emoji_Emoji_range_p,
  __emoji_Emoji_range_q,
  __emoji_Emoji_range_r,
  __emoji_Emoji_range_s,
  __emoji_Emoji_range_t,
  __emoji_Emoji_range_u,
  __emoji_Emoji_range_v,
  __emoji_Emoji_range_w,
  __emoji_Emoji_range_x,
  __emoji_Emoji_range_y,
  __emoji_Emoji_range_z,
  __emoji_Emoji_range_10,
]
private let __emoji_Emoji_ranges = MultipleRanges<Unicode.Scalar.Value>(carefullySortedRanges: __emoji_Emoji_array)
internal let _emoji_Emoji = UnicodeScalarValueSet(singleValues: __emoji_Emoji_set, ranges: __emoji_Emoji_ranges)
/* ********************************************************************************************** */
// Emoji Property: Emoji_Component
private let __emoji_Emoji_Component_set: _T1 = [
  0x23,
  0x2a,
  0x200d,
  0x20e3,
  0xfe0f,
  0x1f9b0,
  0x1f9b1,
  0x1f9b2,
  0x1f9b3,
]
private let __emoji_Emoji_Component_range_0: _T2 = 0x30....0x39
private let __emoji_Emoji_Component_range_1: _T2 = 0x1f1e6....0x1f1ff
private let __emoji_Emoji_Component_range_2: _T2 = 0x1f3fb....0x1f3ff
private let __emoji_Emoji_Component_range_3: _T2 = 0xe0020....0xe007f
private let __emoji_Emoji_Component_array: _T3 = [
  __emoji_Emoji_Component_range_0,
  __emoji_Emoji_Component_range_1,
  __emoji_Emoji_Component_range_2,
  __emoji_Emoji_Component_range_3,
]
private let __emoji_Emoji_Component_ranges = MultipleRanges<Unicode.Scalar.Value>(carefullySortedRanges: __emoji_Emoji_Component_array)
internal let _emoji_Emoji_Component = UnicodeScalarValueSet(singleValues: __emoji_Emoji_Component_set, ranges: __emoji_Emoji_Component_ranges)
/* ********************************************************************************************** */
// Emoji Property: Emoji_Modifier
private let __emoji_Emoji_Modifier_set: _T1 = [
]
private let __emoji_Emoji_Modifier_range_0: _T2 = 0x1f3fb....0x1f3ff
private let __emoji_Emoji_Modifier_array: _T3 = [
  __emoji_Emoji_Modifier_range_0,
]
private let __emoji_Emoji_Modifier_ranges = MultipleRanges<Unicode.Scalar.Value>(carefullySortedRanges: __emoji_Emoji_Modifier_array)
internal let _emoji_Emoji_Modifier = UnicodeScalarValueSet(singleValues: __emoji_Emoji_Modifier_set, ranges: __emoji_Emoji_Modifier_ranges)
/* ********************************************************************************************** */
// Emoji Property: Emoji_Modifier_Base
private let __emoji_Emoji_Modifier_Base_set: _T1 = [
  0x261d,
  0x26f9,
  0x270a,
  0x270b,
  0x270c,
  0x270d,
  0x1f385,
  0x1f3c2,
  0x1f3c3,
  0x1f3c4,
  0x1f3c7,
  0x1f3ca,
  0x1f3cb,
  0x1f3cc,
  0x1f442,
  0x1f443,
  0x1f47c,
  0x1f481,
  0x1f482,
  0x1f483,
  0x1f485,
  0x1f486,
  0x1f487,
  0x1f48f,
  0x1f491,
  0x1f4aa,
  0x1f574,
  0x1f575,
  0x1f57a,
  0x1f590,
  0x1f595,
  0x1f596,
  0x1f645,
  0x1f646,
  0x1f647,
  0x1f6a3,
  0x1f6b4,
  0x1f6b5,
  0x1f6b6,
  0x1f6c0,
  0x1f6cc,
  0x1f90c,
  0x1f90f,
  0x1f926,
  0x1f93c,
  0x1f93d,
  0x1f93e,
  0x1f977,
  0x1f9b5,
  0x1f9b6,
  0x1f9b8,
  0x1f9b9,
  0x1f9bb,
  0x1f9cd,
  0x1f9ce,
  0x1f9cf,
  0x1fac3,
  0x1fac4,
  0x1fac5,
]
private let __emoji_Emoji_Modifier_Base_range_0: _T2 = 0x1f446....0x1f450
private let __emoji_Emoji_Modifier_Base_range_1: _T2 = 0x1f466....0x1f478
private let __emoji_Emoji_Modifier_Base_range_2: _T2 = 0x1f64b....0x1f64f
private let __emoji_Emoji_Modifier_Base_range_3: _T2 = 0x1f918....0x1f91f
private let __emoji_Emoji_Modifier_Base_range_4: _T2 = 0x1f930....0x1f939
private let __emoji_Emoji_Modifier_Base_range_5: _T2 = 0x1f9d1....0x1f9dd
private let __emoji_Emoji_Modifier_Base_range_6: _T2 = 0x1faf0....0x1faf6
private let __emoji_Emoji_Modifier_Base_array: _T3 = [
  __emoji_Emoji_Modifier_Base_range_0,
  __emoji_Emoji_Modifier_Base_range_1,
  __emoji_Emoji_Modifier_Base_range_2,
  __emoji_Emoji_Modifier_Base_range_3,
  __emoji_Emoji_Modifier_Base_range_4,
  __emoji_Emoji_Modifier_Base_range_5,
  __emoji_Emoji_Modifier_Base_range_6,
]
private let __emoji_Emoji_Modifier_Base_ranges = MultipleRanges<Unicode.Scalar.Value>(carefullySortedRanges: __emoji_Emoji_Modifier_Base_array)
internal let _emoji_Emoji_Modifier_Base = UnicodeScalarValueSet(singleValues: __emoji_Emoji_Modifier_Base_set, ranges: __emoji_Emoji_Modifier_Base_ranges)
/* ********************************************************************************************** */
// Emoji Property: Emoji_Presentation
private let __emoji_Emoji_Presentation_set: _T1 = [
  0x231a,
  0x231b,
  0x23e9,
  0x23ea,
  0x23eb,
  0x23ec,
  0x23f0,
  0x23f3,
  0x25fd,
  0x25fe,
  0x2614,
  0x2615,
  0x267f,
  0x2693,
  0x26a1,
  0x26aa,
  0x26ab,
  0x26bd,
  0x26be,
  0x26c4,
  0x26c5,
  0x26ce,
  0x26d4,
  0x26ea,
  0x26f2,
  0x26f3,
  0x26f5,
  0x26fa,
  0x26fd,
  0x2705,
  0x270a,
  0x270b,
  0x2728,
  0x274c,
  0x274e,
  0x2753,
  0x2754,
  0x2755,
  0x2757,
  0x2795,
  0x2796,
  0x2797,
  0x27b0,
  0x27bf,
  0x2b1b,
  0x2b1c,
  0x2b50,
  0x2b55,
  0x1f004,
  0x1f0cf,
  0x1f18e,
  0x1f201,
  0x1f21a,
  0x1f22f,
  0x1f238,
  0x1f239,
  0x1f23a,
  0x1f250,
  0x1f251,
  0x1f3f4,
  0x1f440,
  0x1f54b,
  0x1f54c,
  0x1f54d,
  0x1f54e,
  0x1f57a,
  0x1f595,
  0x1f596,
  0x1f5a4,
  0x1f6cc,
  0x1f6d0,
  0x1f6d1,
  0x1f6d2,
  0x1f6d5,
  0x1f6d6,
  0x1f6d7,
  0x1f6dd,
  0x1f6de,
  0x1f6df,
  0x1f6eb,
  0x1f6ec,
  0x1f7f0,
]
private let __emoji_Emoji_Presentation_range_0: _T2 = 0x2648....0x2653
private let __emoji_Emoji_Presentation_range_1: _T2 = 0x1f191....0x1f19a
private let __emoji_Emoji_Presentation_range_2: _T2 = 0x1f1e6....0x1f1ff
private let __emoji_Emoji_Presentation_range_3: _T2 = 0x1f232....0x1f236
private let __emoji_Emoji_Presentation_range_4: _T2 = 0x1f300....0x1f320
private let __emoji_Emoji_Presentation_range_5: _T2 = 0x1f32d....0x1f335
private let __emoji_Emoji_Presentation_range_6: _T2 = 0x1f337....0x1f37c
private let __emoji_Emoji_Presentation_range_7: _T2 = 0x1f37e....0x1f393
private let __emoji_Emoji_Presentation_range_8: _T2 = 0x1f3a0....0x1f3ca
private let __emoji_Emoji_Presentation_range_9: _T2 = 0x1f3cf....0x1f3d3
private let __emoji_Emoji_Presentation_range_a: _T2 = 0x1f3e0....0x1f3f0
private let __emoji_Emoji_Presentation_range_b: _T2 = 0x1f3f8....0x1f43e
private let __emoji_Emoji_Presentation_range_c: _T2 = 0x1f442....0x1f4fc
private let __emoji_Emoji_Presentation_range_d: _T2 = 0x1f4ff....0x1f53d
private let __emoji_Emoji_Presentation_range_e: _T2 = 0x1f550....0x1f567
private let __emoji_Emoji_Presentation_range_f: _T2 = 0x1f5fb....0x1f64f
private let __emoji_Emoji_Presentation_range_g: _T2 = 0x1f680....0x1f6c5
private let __emoji_Emoji_Presentation_range_h: _T2 = 0x1f6f4....0x1f6fc
private let __emoji_Emoji_Presentation_range_i: _T2 = 0x1f7e0....0x1f7eb
private let __emoji_Emoji_Presentation_range_j: _T2 = 0x1f90c....0x1f93a
private let __emoji_Emoji_Presentation_range_k: _T2 = 0x1f93c....0x1f945
private let __emoji_Emoji_Presentation_range_l: _T2 = 0x1f947....0x1f9ff
private let __emoji_Emoji_Presentation_range_m: _T2 = 0x1fa70....0x1fa74
private let __emoji_Emoji_Presentation_range_n: _T2 = 0x1fa78....0x1fa7c
private let __emoji_Emoji_Presentation_range_o: _T2 = 0x1fa80....0x1fa86
private let __emoji_Emoji_Presentation_range_p: _T2 = 0x1fa90....0x1faac
private let __emoji_Emoji_Presentation_range_q: _T2 = 0x1fab0....0x1faba
private let __emoji_Emoji_Presentation_range_r: _T2 = 0x1fac0....0x1fac5
private let __emoji_Emoji_Presentation_range_s: _T2 = 0x1fad0....0x1fad9
private let __emoji_Emoji_Presentation_range_t: _T2 = 0x1fae0....0x1fae7
private let __emoji_Emoji_Presentation_range_u: _T2 = 0x1faf0....0x1faf6
private let __emoji_Emoji_Presentation_array: _T3 = [
  __emoji_Emoji_Presentation_range_0,
  __emoji_Emoji_Presentation_range_1,
  __emoji_Emoji_Presentation_range_2,
  __emoji_Emoji_Presentation_range_3,
  __emoji_Emoji_Presentation_range_4,
  __emoji_Emoji_Presentation_range_5,
  __emoji_Emoji_Presentation_range_6,
  __emoji_Emoji_Presentation_range_7,
  __emoji_Emoji_Presentation_range_8,
  __emoji_Emoji_Presentation_range_9,
  __emoji_Emoji_Presentation_range_a,
  __emoji_Emoji_Presentation_range_b,
  __emoji_Emoji_Presentation_range_c,
  __emoji_Emoji_Presentation_range_d,
  __emoji_Emoji_Presentation_range_e,
  __emoji_Emoji_Presentation_range_f,
  __emoji_Emoji_Presentation_range_g,
  __emoji_Emoji_Presentation_range_h,
  __emoji_Emoji_Presentation_range_i,
  __emoji_Emoji_Presentation_range_j,
  __emoji_Emoji_Presentation_range_k,
  __emoji_Emoji_Presentation_range_l,
  __emoji_Emoji_Presentation_range_m,
  __emoji_Emoji_Presentation_range_n,
  __emoji_Emoji_Presentation_range_o,
  __emoji_Emoji_Presentation_range_p,
  __emoji_Emoji_Presentation_range_q,
  __emoji_Emoji_Presentation_range_r,
  __emoji_Emoji_Presentation_range_s,
  __emoji_Emoji_Presentation_range_t,
  __emoji_Emoji_Presentation_range_u,
]
private let __emoji_Emoji_Presentation_ranges = MultipleRanges<Unicode.Scalar.Value>(carefullySortedRanges: __emoji_Emoji_Presentation_array)
internal let _emoji_Emoji_Presentation = UnicodeScalarValueSet(singleValues: __emoji_Emoji_Presentation_set, ranges: __emoji_Emoji_Presentation_ranges)
/* ********************************************************************************************** */
// Emoji Property: Extended_Pictographic
private let __emoji_Extended_Pictographic_set: _T1 = [
  0xa9,
  0xae,
  0x203c,
  0x2049,
  0x2122,
  0x2139,
  0x21a9,
  0x21aa,
  0x231a,
  0x231b,
  0x2328,
  0x2388,
  0x23cf,
  0x23f8,
  0x23f9,
  0x23fa,
  0x24c2,
  0x25aa,
  0x25ab,
  0x25b6,
  0x25c0,
  0x25fb,
  0x25fc,
  0x25fd,
  0x25fe,
  0x2714,
  0x2716,
  0x271d,
  0x2721,
  0x2728,
  0x2733,
  0x2734,
  0x2744,
  0x2747,
  0x274c,
  0x274e,
  0x2753,
  0x2754,
  0x2755,
  0x2757,
  0x2795,
  0x2796,
  0x2797,
  0x27a1,
  0x27b0,
  0x27bf,
  0x2934,
  0x2935,
  0x2b05,
  0x2b06,
  0x2b07,
  0x2b1b,
  0x2b1c,
  0x2b50,
  0x2b55,
  0x3030,
  0x303d,
  0x3297,
  0x3299,
  0x1f10d,
  0x1f10e,
  0x1f10f,
  0x1f12f,
  0x1f17e,
  0x1f17f,
  0x1f18e,
  0x1f21a,
  0x1f22f,
  0x1f23c,
  0x1f23d,
  0x1f23e,
  0x1f23f,
  0x1f80c,
  0x1f80d,
  0x1f80e,
  0x1f80f,
]
private let __emoji_Extended_Pictographic_range_0: _T2 = 0x2194....0x2199
private let __emoji_Extended_Pictographic_range_1: _T2 = 0x23e9....0x23f3
private let __emoji_Extended_Pictographic_range_2: _T2 = 0x2600....0x2605
private let __emoji_Extended_Pictographic_range_3: _T2 = 0x2607....0x2612
private let __emoji_Extended_Pictographic_range_4: _T2 = 0x2614....0x2685
private let __emoji_Extended_Pictographic_range_5: _T2 = 0x2690....0x2705
private let __emoji_Extended_Pictographic_range_6: _T2 = 0x2708....0x2712
private let __emoji_Extended_Pictographic_range_7: _T2 = 0x2763....0x2767
private let __emoji_Extended_Pictographic_range_8: _T2 = 0x1f000....0x1f0ff
private let __emoji_Extended_Pictographic_range_9: _T2 = 0x1f16c....0x1f171
private let __emoji_Extended_Pictographic_range_a: _T2 = 0x1f191....0x1f19a
private let __emoji_Extended_Pictographic_range_b: _T2 = 0x1f1ad....0x1f1e5
private let __emoji_Extended_Pictographic_range_c: _T2 = 0x1f201....0x1f20f
private let __emoji_Extended_Pictographic_range_d: _T2 = 0x1f232....0x1f23a
private let __emoji_Extended_Pictographic_range_e: _T2 = 0x1f249....0x1f3fa
private let __emoji_Extended_Pictographic_range_f: _T2 = 0x1f400....0x1f53d
private let __emoji_Extended_Pictographic_range_g: _T2 = 0x1f546....0x1f64f
private let __emoji_Extended_Pictographic_range_h: _T2 = 0x1f680....0x1f6ff
private let __emoji_Extended_Pictographic_range_i: _T2 = 0x1f774....0x1f77f
private let __emoji_Extended_Pictographic_range_j: _T2 = 0x1f7d5....0x1f7ff
private let __emoji_Extended_Pictographic_range_k: _T2 = 0x1f848....0x1f84f
private let __emoji_Extended_Pictographic_range_l: _T2 = 0x1f85a....0x1f85f
private let __emoji_Extended_Pictographic_range_m: _T2 = 0x1f888....0x1f88f
private let __emoji_Extended_Pictographic_range_n: _T2 = 0x1f8ae....0x1f8ff
private let __emoji_Extended_Pictographic_range_o: _T2 = 0x1f90c....0x1f93a
private let __emoji_Extended_Pictographic_range_p: _T2 = 0x1f93c....0x1f945
private let __emoji_Extended_Pictographic_range_q: _T2 = 0x1f947....0x1faff
private let __emoji_Extended_Pictographic_range_r: _T2 = 0x1fc00....0x1fffd
private let __emoji_Extended_Pictographic_array: _T3 = [
  __emoji_Extended_Pictographic_range_0,
  __emoji_Extended_Pictographic_range_1,
  __emoji_Extended_Pictographic_range_2,
  __emoji_Extended_Pictographic_range_3,
  __emoji_Extended_Pictographic_range_4,
  __emoji_Extended_Pictographic_range_5,
  __emoji_Extended_Pictographic_range_6,
  __emoji_Extended_Pictographic_range_7,
  __emoji_Extended_Pictographic_range_8,
  __emoji_Extended_Pictographic_range_9,
  __emoji_Extended_Pictographic_range_a,
  __emoji_Extended_Pictographic_range_b,
  __emoji_Extended_Pictographic_range_c,
  __emoji_Extended_Pictographic_range_d,
  __emoji_Extended_Pictographic_range_e,
  __emoji_Extended_Pictographic_range_f,
  __emoji_Extended_Pictographic_range_g,
  __emoji_Extended_Pictographic_range_h,
  __emoji_Extended_Pictographic_range_i,
  __emoji_Extended_Pictographic_range_j,
  __emoji_Extended_Pictographic_range_k,
  __emoji_Extended_Pictographic_range_l,
  __emoji_Extended_Pictographic_range_m,
  __emoji_Extended_Pictographic_range_n,
  __emoji_Extended_Pictographic_range_o,
  __emoji_Extended_Pictographic_range_p,
  __emoji_Extended_Pictographic_range_q,
  __emoji_Extended_Pictographic_range_r,
]
private let __emoji_Extended_Pictographic_ranges = MultipleRanges<Unicode.Scalar.Value>(carefullySortedRanges: __emoji_Extended_Pictographic_array)
internal let _emoji_Extended_Pictographic = UnicodeScalarValueSet(singleValues: __emoji_Extended_Pictographic_set, ranges: __emoji_Extended_Pictographic_ranges)
