#if !canImport(ObjectiveC)
import XCTest

extension UnicodeSupplementUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnicodeSupplementUpdaterTests = [
        ("test_bidiClass", test_bidiClass),
        ("test_binProp", test_binProp),
        ("test_ccc", test_ccc),
        ("test_coreProp", test_coreProp),
        ("test_gc", test_gc),
        ("test_jg", test_jg),
        ("test_jt", test_jt),
        ("test_propertyValueAliases", test_propertyValueAliases),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UnicodeSupplementUpdaterTests.__allTests__UnicodeSupplementUpdaterTests),
    ]
}
#endif
