#if !canImport(ObjectiveC)
import XCTest

extension UnicodeSupplementUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnicodeSupplementUpdaterTests = [
        ("test_binProp", test_binProp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UnicodeSupplementUpdaterTests.__allTests__UnicodeSupplementUpdaterTests),
    ]
}
#endif
